const withRewrites = {
  async rewrites() {
    const identityUrl = process.env.IDENTITY_SERVICE_URL || "http://localhost:8081";
    const academyUrl = process.env.ACADEMY_SERVICE_URL || "http://localhost:8082";
    const paymentUrl = process.env.PAYMENT_SERVICE_URL || "http://localhost:8083";
    const payrollUrl = process.env.PAYROLL_SERVICE_URL || "http://localhost:8084";
    const attendanceUrl = process.env.ATTENDANCE_SERVICE_URL || "http://localhost:8085";
    const connectUrl = process.env.CONNECT_SERVICE_URL || "http://localhost:8086";
    const aiGatewayUrl = process.env.AI_GATEWAY_URL || "http://localhost:8087";
    const ruleEngineUrl = process.env.RULE_ENGINE_URL || "http://localhost:8088";
    const socialMediaUrl = process.env.SOCIAL_MEDIA_SERVICE_URL || "http://localhost:8089";

    // Simple path-based routing by domain area. This lets the frontend call relative URLs.
    // Note: Both exact paths and :path* patterns needed for Next.js rewrites to work properly
    return [
      // Identity/auth & org setup
      { source: "/api/auth", destination: `${identityUrl}/api/auth` },
      { source: "/api/auth/:path*", destination: `${identityUrl}/api/auth/:path*` },
      { source: "/api/users", destination: `${identityUrl}/api/users` },
      { source: "/api/users/:path*", destination: `${identityUrl}/api/users/:path*` },
      { source: "/api/roles", destination: `${identityUrl}/api/roles` },
      { source: "/api/roles/:path*", destination: `${identityUrl}/api/roles/:path*` },
      { source: "/api/centers", destination: `${identityUrl}/api/centers` },
      { source: "/api/centers/:path*", destination: `${identityUrl}/api/centers/:path*` },
      { source: "/api/departments", destination: `${identityUrl}/api/departments` },
      { source: "/api/departments/:path*", destination: `${identityUrl}/api/departments/:path*` },
      { source: "/api/impersonation", destination: `${identityUrl}/api/impersonation` },
      { source: "/api/impersonation/:path*", destination: `${identityUrl}/api/impersonation/:path*` },
      { source: "/api/user-permissions", destination: `${identityUrl}/api/user-permissions` },
      { source: "/api/user-permissions/:path*", destination: `${identityUrl}/api/user-permissions/:path*` },
      { source: "/api/activity-logs", destination: `${identityUrl}/api/activity-logs` },
      { source: "/api/activity-logs/:path*", destination: `${identityUrl}/api/activity-logs/:path*` },
      { source: "/api/system-settings", destination: `${identityUrl}/api/system-settings` },
      { source: "/api/system-settings/:path*", destination: `${identityUrl}/api/system-settings/:path*` },
      { source: "/api/approvals", destination: `${identityUrl}/api/approvals` },
      { source: "/api/approvals/:path*", destination: `${identityUrl}/api/approvals/:path*` },
      { source: "/api/audit-logs", destination: `${identityUrl}/api/audit-logs` },
      { source: "/api/audit-logs/:path*", destination: `${identityUrl}/api/audit-logs/:path*` },
      { source: "/api/dashboard", destination: `${identityUrl}/api/dashboard` },
      { source: "/api/dashboard/:path*", destination: `${identityUrl}/api/dashboard/:path*` },
      { source: "/api/health", destination: `${identityUrl}/api/health` },
      { source: "/api/health/:path*", destination: `${identityUrl}/api/health/:path*` },
      // /api/me and /api/profile rewrites removed — no backend controller
      // exists for either path. The frontend uses /api/users/me/settings and
      // /api/users/me/change-password, which are routed via the /api/users
      // entries above.
      // Additional Identity routes
      { source: "/api/staff", destination: `${identityUrl}/api/staff` },
      { source: "/api/staff/:path*", destination: `${identityUrl}/api/staff/:path*` },
      { source: "/api/tenants", destination: `${identityUrl}/api/tenants` },
      { source: "/api/tenants/:path*", destination: `${identityUrl}/api/tenants/:path*` },
      { source: "/api/permissions", destination: `${identityUrl}/api/permissions` },
      { source: "/api/permissions/:path*", destination: `${identityUrl}/api/permissions/:path*` },
      { source: "/api/feature-flags", destination: `${identityUrl}/api/feature-flags` },
      { source: "/api/feature-flags/:path*", destination: `${identityUrl}/api/feature-flags/:path*` },
      { source: "/api/website-settings", destination: `${identityUrl}/api/website-settings` },
      { source: "/api/website-settings/:path*", destination: `${identityUrl}/api/website-settings/:path*` },
      { source: "/api/login-history", destination: `${identityUrl}/api/login-history` },
      { source: "/api/login-history/:path*", destination: `${identityUrl}/api/login-history/:path*` },
      { source: "/api/tenant-settings", destination: `${identityUrl}/api/tenant-settings` },
      { source: "/api/tenant-settings/:path*", destination: `${identityUrl}/api/tenant-settings/:path*` },
      // Additional Identity routes - User Roles
      { source: "/api/user-roles", destination: `${identityUrl}/api/user-roles` },
      { source: "/api/user-roles/:path*", destination: `${identityUrl}/api/user-roles/:path*` },
      // Custom Fields - routes to identity service
      { source: "/api/custom-fields", destination: `${identityUrl}/api/custom-fields` },
      { source: "/api/custom-fields/:path*", destination: `${identityUrl}/api/custom-fields/:path*` },
      { source: "/api/custom-field-values", destination: `${identityUrl}/api/custom-field-values` },
      { source: "/api/custom-field-values/:path*", destination: `${identityUrl}/api/custom-field-values/:path*` },
      // Dropdown Options - routes to identity service
      { source: "/api/dropdown-options", destination: `${identityUrl}/api/dropdown-options` },
      { source: "/api/dropdown-options/:path*", destination: `${identityUrl}/api/dropdown-options/:path*` },

      // File Upload + stored assets (local backend serves /uploads/**)
      { source: "/api/upload", destination: `${academyUrl}/api/upload` },
      { source: "/api/upload/:path*", destination: `${academyUrl}/api/upload/:path*` },
      { source: "/api/report-cards", destination: `${academyUrl}/api/report-cards` },
      { source: "/api/report-cards/:path*", destination: `${academyUrl}/api/report-cards/:path*` },
      { source: "/uploads/:path*", destination: `${academyUrl}/uploads/:path*` },

      // Academy core
      { source: "/api/students", destination: `${academyUrl}/api/students` },
      { source: "/api/students/:path*", destination: `${academyUrl}/api/students/:path*` },
      { source: "/api/teachers", destination: `${academyUrl}/api/teachers` },
      { source: "/api/teachers/:path*", destination: `${academyUrl}/api/teachers/:path*` },
      { source: "/api/student-parents", destination: `${academyUrl}/api/student-parents` },
      { source: "/api/student-parents/:path*", destination: `${academyUrl}/api/student-parents/:path*` },
      { source: "/api/parent-students", destination: `${academyUrl}/api/parent-students` },
      { source: "/api/parent-students/:path*", destination: `${academyUrl}/api/parent-students/:path*` },
      { source: "/api/courses", destination: `${academyUrl}/api/courses` },
      { source: "/api/courses/:path*", destination: `${academyUrl}/api/courses/:path*` },
      { source: "/api/classes", destination: `${academyUrl}/api/classes` },
      { source: "/api/classes/:path*", destination: `${academyUrl}/api/classes/:path*` },
      { source: "/api/enrollments", destination: `${academyUrl}/api/enrollments` },
      { source: "/api/enrollments/:path*", destination: `${academyUrl}/api/enrollments/:path*` },
      { source: "/api/renewals", destination: `${academyUrl}/api/renewals` },
      { source: "/api/renewals/:path*", destination: `${academyUrl}/api/renewals/:path*` },
      { source: "/api/training-sessions", destination: `${academyUrl}/api/training-sessions` },
      { source: "/api/training-sessions/:path*", destination: `${academyUrl}/api/training-sessions/:path*` },
      { source: "/api/staff-certifications", destination: `${academyUrl}/api/staff-certifications` },
      { source: "/api/staff-certifications/:path*", destination: `${academyUrl}/api/staff-certifications/:path*` },
      { source: "/api/performance-reviews", destination: `${academyUrl}/api/performance-reviews` },
      { source: "/api/performance-reviews/:path*", destination: `${academyUrl}/api/performance-reviews/:path*` },
      { source: "/api/job-openings", destination: `${academyUrl}/api/job-openings` },
      { source: "/api/job-openings/:path*", destination: `${academyUrl}/api/job-openings/:path*` },
      { source: "/api/assignments", destination: `${academyUrl}/api/assignments` },
      { source: "/api/assignments/:path*", destination: `${academyUrl}/api/assignments/:path*` },
      { source: "/api/lesson-plans", destination: `${academyUrl}/api/lesson-plans` },
      { source: "/api/lesson-plans/:path*", destination: `${academyUrl}/api/lesson-plans/:path*` },
      { source: "/api/exams", destination: `${academyUrl}/api/exams` },
      { source: "/api/exams/:path*", destination: `${academyUrl}/api/exams/:path*` },
      { source: "/api/exam-results", destination: `${academyUrl}/api/exam-results` },
      { source: "/api/exam-results/:path*", destination: `${academyUrl}/api/exam-results/:path*` },
      { source: "/api/curriculum", destination: `${academyUrl}/api/curriculum` },
      { source: "/api/curriculum/:path*", destination: `${academyUrl}/api/curriculum/:path*` },
      { source: "/api/books", destination: `${academyUrl}/api/books` },
      { source: "/api/books/:path*", destination: `${academyUrl}/api/books/:path*` },
      { source: "/api/certificates", destination: `${academyUrl}/api/certificates` },
      { source: "/api/certificates/:path*", destination: `${academyUrl}/api/certificates/:path*` },
      { source: "/api/transport", destination: `${academyUrl}/api/transport` },
      { source: "/api/transport/:path*", destination: `${academyUrl}/api/transport/:path*` },
      { source: "/api/gamification", destination: `${academyUrl}/api/gamification` },
      { source: "/api/gamification/:path*", destination: `${academyUrl}/api/gamification/:path*` },
      { source: "/api/schedules", destination: `${academyUrl}/api/schedules` },
      { source: "/api/schedules/:path*", destination: `${academyUrl}/api/schedules/:path*` },
      { source: "/api/timetable", destination: `${academyUrl}/api/timetable` },
      { source: "/api/timetable/:path*", destination: `${academyUrl}/api/timetable/:path*` },
      { source: "/api/calendar", destination: `${academyUrl}/api/calendar` },
      { source: "/api/calendar/:path*", destination: `${academyUrl}/api/calendar/:path*` },
      { source: "/api/grades", destination: `${academyUrl}/api/grades` },
      { source: "/api/grades/:path*", destination: `${academyUrl}/api/grades/:path*` },
      { source: "/api/programs", destination: `${academyUrl}/api/programs` },
      { source: "/api/programs/:path*", destination: `${academyUrl}/api/programs/:path*` },
      { source: "/api/classrooms", destination: `${academyUrl}/api/classes` },
      { source: "/api/classrooms/:path*", destination: `${academyUrl}/api/classes/:path*` },
      // Reports
      { source: "/api/reports", destination: `${academyUrl}/api/reports` },
      { source: "/api/reports/:path*", destination: `${academyUrl}/api/reports/:path*` },
      { source: "/api/referrals", destination: `${academyUrl}/api/referrals` },
      { source: "/api/referrals/:path*", destination: `${academyUrl}/api/referrals/:path*` },

      // Academy CMS/public website
      { source: "/api/cms-settings", destination: `${academyUrl}/api/cms-settings` },
      { source: "/api/cms-settings/:path*", destination: `${academyUrl}/api/cms-settings/:path*` },
      { source: "/api/banners", destination: `${academyUrl}/api/banners` },
      { source: "/api/banners/:path*", destination: `${academyUrl}/api/banners/:path*` },
      { source: "/api/testimonials", destination: `${academyUrl}/api/testimonials` },
      { source: "/api/testimonials/:path*", destination: `${academyUrl}/api/testimonials/:path*` },
      { source: "/api/blog", destination: `${academyUrl}/api/blog` },
      { source: "/api/blog/:path*", destination: `${academyUrl}/api/blog/:path*` },
      { source: "/api/contact", destination: `${academyUrl}/api/contact` },
      { source: "/api/contact/:path*", destination: `${academyUrl}/api/contact/:path*` },
      // CRM leads from public marketing site (Connect). Must be before generic /api/public/* → academy.
      { source: "/api/public/leads", destination: `${connectUrl}/api/public/leads` },
      // Public enrolment payment funnel (Payment service) — must also precede the generic /api/public/*.
      { source: "/api/public/payment/:path*", destination: `${paymentUrl}/api/public/payment/:path*` },
      { source: "/api/public", destination: `${academyUrl}/api/public` },
      { source: "/api/public/:path*", destination: `${academyUrl}/api/public/:path*` },
      { source: "/api/faqs", destination: `${academyUrl}/api/faqs` },
      { source: "/api/faqs/:path*", destination: `${academyUrl}/api/faqs/:path*` },
      { source: "/api/feedback", destination: `${academyUrl}/api/feedback` },
      { source: "/api/feedback/:path*", destination: `${academyUrl}/api/feedback/:path*` },
      { source: "/api/leadership-members", destination: `${academyUrl}/api/leadership-members` },
      { source: "/api/leadership-members/:path*", destination: `${academyUrl}/api/leadership-members/:path*` },
      // Additional Academy routes - Library
      { source: "/api/book-borrowings", destination: `${academyUrl}/api/book-borrowings` },
      { source: "/api/book-borrowings/:path*", destination: `${academyUrl}/api/book-borrowings/:path*` },
      { source: "/api/book-reservations", destination: `${academyUrl}/api/book-reservations` },
      { source: "/api/book-reservations/:path*", destination: `${academyUrl}/api/book-reservations/:path*` },
      { source: "/api/book-categories", destination: `${academyUrl}/api/book-categories` },
      { source: "/api/book-categories/:path*", destination: `${academyUrl}/api/book-categories/:path*` },
      { source: "/api/library-fines", destination: `${academyUrl}/api/library-fines` },
      { source: "/api/library-fines/:path*", destination: `${academyUrl}/api/library-fines/:path*` },
      { source: "/api/library-inventory", destination: `${academyUrl}/api/library-inventory` },
      { source: "/api/library-inventory/:path*", destination: `${academyUrl}/api/library-inventory/:path*` },
      { source: "/api/library", destination: `${academyUrl}/api/library` },
      { source: "/api/library/:path*", destination: `${academyUrl}/api/library/:path*` },
      { source: "/api/hostel", destination: `${academyUrl}/api/hostel` },
      { source: "/api/hostel/:path*", destination: `${academyUrl}/api/hostel/:path*` },
      { source: "/api/bookstore", destination: `${academyUrl}/api/bookstore` },
      { source: "/api/bookstore/:path*", destination: `${academyUrl}/api/bookstore/:path*` },
      { source: "/api/authors", destination: `${academyUrl}/api/authors` },
      { source: "/api/authors/:path*", destination: `${academyUrl}/api/authors/:path*` },
      { source: "/api/publishers", destination: `${academyUrl}/api/publishers` },
      { source: "/api/publishers/:path*", destination: `${academyUrl}/api/publishers/:path*` },
      // Additional Academy routes - Transport
      { source: "/api/vehicles", destination: `${academyUrl}/api/vehicles` },
      { source: "/api/vehicles/:path*", destination: `${academyUrl}/api/vehicles/:path*` },
      { source: "/api/drivers", destination: `${academyUrl}/api/drivers` },
      { source: "/api/drivers/:path*", destination: `${academyUrl}/api/drivers/:path*` },
      { source: "/api/route-stops", destination: `${academyUrl}/api/route-stops` },
      { source: "/api/route-stops/:path*", destination: `${academyUrl}/api/route-stops/:path*` },
      { source: "/api/transport-schedules", destination: `${academyUrl}/api/transport-schedules` },
      { source: "/api/transport-schedules/:path*", destination: `${academyUrl}/api/transport-schedules/:path*` },
      { source: "/api/transport-attendance", destination: `${academyUrl}/api/transport-attendance` },
      { source: "/api/transport-attendance/:path*", destination: `${academyUrl}/api/transport-attendance/:path*` },
      { source: "/api/vehicle-maintenance", destination: `${academyUrl}/api/vehicle-maintenance` },
      { source: "/api/vehicle-maintenance/:path*", destination: `${academyUrl}/api/vehicle-maintenance/:path*` },
      { source: "/api/gps-tracking", destination: `${academyUrl}/api/gps-tracking` },
      { source: "/api/gps-tracking/:path*", destination: `${academyUrl}/api/gps-tracking/:path*` },
      { source: "/api/student-transport", destination: `${academyUrl}/api/student-transport` },
      { source: "/api/student-transport/:path*", destination: `${academyUrl}/api/student-transport/:path*` },
      // Additional Academy routes - Sports
      { source: "/api/sports", destination: `${academyUrl}/api/sports` },
      { source: "/api/sports/:path*", destination: `${academyUrl}/api/sports/:path*` },
      { source: "/api/sport-teams", destination: `${academyUrl}/api/sport-teams` },
      { source: "/api/sport-teams/:path*", destination: `${academyUrl}/api/sport-teams/:path*` },
      { source: "/api/sport-matches", destination: `${academyUrl}/api/sport-matches` },
      { source: "/api/sport-matches/:path*", destination: `${academyUrl}/api/sport-matches/:path*` },
      { source: "/api/tournaments", destination: `${academyUrl}/api/tournaments` },
      { source: "/api/tournaments/:path*", destination: `${academyUrl}/api/tournaments/:path*` },
      { source: "/api/sport-facilities", destination: `${academyUrl}/api/sport-facilities` },
      { source: "/api/sport-facilities/:path*", destination: `${academyUrl}/api/sport-facilities/:path*` },
      // Additional Academy routes - Other
      { source: "/api/class-sessions", destination: `${academyUrl}/api/class-sessions` },
      { source: "/api/class-sessions/:path*", destination: `${academyUrl}/api/class-sessions/:path*` },
      { source: "/api/class-schedules", destination: `${academyUrl}/api/class-schedules` },
      { source: "/api/class-schedules/:path*", destination: `${academyUrl}/api/class-schedules/:path*` },
      { source: "/api/certificate-templates", destination: `${academyUrl}/api/certificate-templates` },
      { source: "/api/certificate-templates/:path*", destination: `${academyUrl}/api/certificate-templates/:path*` },
      { source: "/api/media-gallery", destination: `${academyUrl}/api/media-gallery` },
      { source: "/api/media-gallery/:path*", destination: `${academyUrl}/api/media-gallery/:path*` },
      { source: "/api/facility-bookings", destination: `${academyUrl}/api/facility-bookings` },
      { source: "/api/facility-bookings/:path*", destination: `${academyUrl}/api/facility-bookings/:path*` },
      { source: "/api/excel-import", destination: `${academyUrl}/api/excel-import` },
      { source: "/api/excel-import/:path*", destination: `${academyUrl}/api/excel-import/:path*` },
      // User activity tracking
      { source: "/api/user-activity", destination: `${academyUrl}/api/user-activity` },
      { source: "/api/user-activity/:path*", destination: `${academyUrl}/api/user-activity/:path*` },
      { source: "/api/class-switch", destination: `${academyUrl}/api/class-switch` },
      { source: "/api/class-switch/:path*", destination: `${academyUrl}/api/class-switch/:path*` },
      // Additional Academy routes - Course Management
      { source: "/api/course-modules", destination: `${academyUrl}/api/course-modules` },
      { source: "/api/course-modules/:path*", destination: `${academyUrl}/api/course-modules/:path*` },
      { source: "/api/course-lessons", destination: `${academyUrl}/api/course-lessons` },
      { source: "/api/course-lessons/:path*", destination: `${academyUrl}/api/course-lessons/:path*` },
      { source: "/api/course-materials", destination: `${academyUrl}/api/course-materials` },
      { source: "/api/course-materials/:path*", destination: `${academyUrl}/api/course-materials/:path*` },
      // Additional Academy routes - Documents
      { source: "/api/student-documents", destination: `${academyUrl}/api/student-documents` },
      { source: "/api/student-documents/:path*", destination: `${academyUrl}/api/student-documents/:path*` },
      { source: "/api/teacher-documents", destination: `${academyUrl}/api/teacher-documents` },
      { source: "/api/teacher-documents/:path*", destination: `${academyUrl}/api/teacher-documents/:path*` },
      // Additional Academy routes - Points & Skills
      { source: "/api/student-points", destination: `${academyUrl}/api/student-points` },
      { source: "/api/student-points/:path*", destination: `${academyUrl}/api/student-points/:path*` },
      { source: "/api/point-transactions", destination: `${academyUrl}/api/point-transactions` },
      { source: "/api/point-transactions/:path*", destination: `${academyUrl}/api/point-transactions/:path*` },
      { source: "/api/student-skill-levels", destination: `${academyUrl}/api/student-skill-levels` },
      { source: "/api/student-skill-levels/:path*", destination: `${academyUrl}/api/student-skill-levels/:path*` },
      { source: "/api/teacher-skill-levels", destination: `${academyUrl}/api/teacher-skill-levels` },
      { source: "/api/teacher-skill-levels/:path*", destination: `${academyUrl}/api/teacher-skill-levels/:path*` },
      // Additional Academy routes - Center & Settings
      { source: "/api/center-settings", destination: `${academyUrl}/api/center-settings` },
      { source: "/api/center-settings/:path*", destination: `${academyUrl}/api/center-settings/:path*` },
      { source: "/api/form-configs", destination: `${academyUrl}/api/form-configs` },
      { source: "/api/form-configs/:path*", destination: `${academyUrl}/api/form-configs/:path*` },
      // Additional Academy routes - Transport Extended
      { source: "/api/transport-routes", destination: `${academyUrl}/api/transport-routes` },
      { source: "/api/transport-routes/:path*", destination: `${academyUrl}/api/transport-routes/:path*` },
      { source: "/api/transport-drivers", destination: `${academyUrl}/api/transport-drivers` },
      { source: "/api/transport-drivers/:path*", destination: `${academyUrl}/api/transport-drivers/:path*` },
      // Additional Academy routes - CMS Extended
      { source: "/api/cms-pages", destination: `${academyUrl}/api/cms-pages` },
      { source: "/api/cms-pages/:path*", destination: `${academyUrl}/api/cms-pages/:path*` },
      { source: "/api/footer-settings", destination: `${academyUrl}/api/footer-settings` },
      { source: "/api/footer-settings/:path*", destination: `${academyUrl}/api/footer-settings/:path*` },
      // Additional Academy routes - Registration & Import
      { source: "/api/student-registrations", destination: `${academyUrl}/api/student-registrations` },
      { source: "/api/student-registrations/:path*", destination: `${academyUrl}/api/student-registrations/:path*` },
      { source: "/api/import", destination: `${academyUrl}/api/import` },
      { source: "/api/import/:path*", destination: `${academyUrl}/api/import/:path*` },
      // Additional Academy routes - Sports Extended
      { source: "/api/sport-types", destination: `${academyUrl}/api/sport-types` },
      { source: "/api/sport-types/:path*", destination: `${academyUrl}/api/sport-types/:path*` },
      { source: "/api/sport-equipment", destination: `${academyUrl}/api/sport-equipment` },
      { source: "/api/sport-equipment/:path*", destination: `${academyUrl}/api/sport-equipment/:path*` },
      { source: "/api/sport-training-sessions", destination: `${academyUrl}/api/sport-training-sessions` },
      { source: "/api/sport-training-sessions/:path*", destination: `${academyUrl}/api/sport-training-sessions/:path*` },
      { source: "/api/training-attendance", destination: `${academyUrl}/api/training-attendance` },
      { source: "/api/training-attendance/:path*", destination: `${academyUrl}/api/training-attendance/:path*` },
      { source: "/api/player-statistics", destination: `${academyUrl}/api/player-statistics` },
      { source: "/api/player-statistics/:path*", destination: `${academyUrl}/api/player-statistics/:path*` },
      { source: "/api/equipment-assignments", destination: `${academyUrl}/api/equipment-assignments` },
      { source: "/api/equipment-assignments/:path*", destination: `${academyUrl}/api/equipment-assignments/:path*` },
      { source: "/api/team-members", destination: `${academyUrl}/api/team-members` },
      { source: "/api/team-members/:path*", destination: `${academyUrl}/api/team-members/:path*` },
      { source: "/api/match-events", destination: `${academyUrl}/api/match-events` },
      { source: "/api/match-events/:path*", destination: `${academyUrl}/api/match-events/:path*` },
      { source: "/api/tournament-teams", destination: `${academyUrl}/api/tournament-teams` },
      { source: "/api/tournament-teams/:path*", destination: `${academyUrl}/api/tournament-teams/:path*` },
      // Additional Academy routes - Session & Attendance
      { source: "/api/session-attendance", destination: `${academyUrl}/api/session-attendance` },
      { source: "/api/session-attendance/:path*", destination: `${academyUrl}/api/session-attendance/:path*` },
      { source: "/api/class-schedule-exceptions", destination: `${academyUrl}/api/class-schedule-exceptions` },
      { source: "/api/class-schedule-exceptions/:path*", destination: `${academyUrl}/api/class-schedule-exceptions/:path*` },
      // Additional Academy routes - Assignments & Media
      { source: "/api/assignment-submissions", destination: `${academyUrl}/api/assignment-submissions` },
      { source: "/api/assignment-submissions/:path*", destination: `${academyUrl}/api/assignment-submissions/:path*` },
      { source: "/api/media", destination: `${academyUrl}/api/media` },
      { source: "/api/media/:path*", destination: `${academyUrl}/api/media/:path*` },
      // Additional Academy routes - Parents
      { source: "/api/parents", destination: `${academyUrl}/api/parents` },
      { source: "/api/parents/:path*", destination: `${academyUrl}/api/parents/:path*` },
      // Permission slips (parent consent flow) — academy_service owns this
      { source: "/api/permission-slips", destination: `${academyUrl}/api/permission-slips` },
      { source: "/api/permission-slips/:path*", destination: `${academyUrl}/api/permission-slips/:path*` },

      // Payments
      { source: "/api/payments", destination: `${paymentUrl}/api/payments` },
      { source: "/api/payments/:path*", destination: `${paymentUrl}/api/payments/:path*` },
      { source: "/api/invoices", destination: `${paymentUrl}/api/invoices` },
      { source: "/api/invoices/:path*", destination: `${paymentUrl}/api/invoices/:path*` },
      { source: "/api/fee-rules", destination: `${paymentUrl}/api/fee-rules` },
      { source: "/api/fee-rules/:path*", destination: `${paymentUrl}/api/fee-rules/:path*` },
      { source: "/api/discounts", destination: `${paymentUrl}/api/discounts` },
      { source: "/api/discounts/:path*", destination: `${paymentUrl}/api/discounts/:path*` },
      { source: "/api/refunds", destination: `${paymentUrl}/api/refunds` },
      { source: "/api/refunds/:path*", destination: `${paymentUrl}/api/refunds/:path*` },
      { source: "/api/student-fee-plans", destination: `${paymentUrl}/api/student-fee-plans` },
      { source: "/api/student-fee-plans/:path*", destination: `${paymentUrl}/api/student-fee-plans/:path*` },
      { source: "/api/student-discounts", destination: `${paymentUrl}/api/student-discounts` },
      { source: "/api/student-discounts/:path*", destination: `${paymentUrl}/api/student-discounts/:path*` },
      { source: "/api/finance", destination: `${paymentUrl}/api/finance` },
      { source: "/api/finance/:path*", destination: `${paymentUrl}/api/finance/:path*` },
      // /api/fee-structures rewrites removed — payment_service has no
      // FeeStructureController (the comparable feature lives at
      // /api/fee-rules → FeeRuleController). Frontend uses /api/fee-rules.
      // Additional Payment routes
      { source: "/api/scholarships", destination: `${paymentUrl}/api/scholarships` },
      { source: "/api/scholarships/:path*", destination: `${paymentUrl}/api/scholarships/:path*` },
      { source: "/api/student-scholarships", destination: `${paymentUrl}/api/student-scholarships` },
      { source: "/api/student-scholarships/:path*", destination: `${paymentUrl}/api/student-scholarships/:path*` },
      { source: "/api/ledger", destination: `${paymentUrl}/api/ledger` },
      { source: "/api/ledger/:path*", destination: `${paymentUrl}/api/ledger/:path*` },
      { source: "/api/payment-methods", destination: `${paymentUrl}/api/payment-methods` },
      { source: "/api/payment-methods/:path*", destination: `${paymentUrl}/api/payment-methods/:path*` },
      { source: "/api/late-fee-rules", destination: `${paymentUrl}/api/late-fee-rules` },
      { source: "/api/late-fee-rules/:path*", destination: `${paymentUrl}/api/late-fee-rules/:path*` },
      { source: "/api/fee-receipts", destination: `${paymentUrl}/api/fee-receipts` },
      { source: "/api/fee-receipts/:path*", destination: `${paymentUrl}/api/fee-receipts/:path*` },

      // Attendance & Leave
      { source: "/api/attendance", destination: `${attendanceUrl}/api/attendance` },
      { source: "/api/attendance/:path*", destination: `${attendanceUrl}/api/attendance/:path*` },
      { source: "/api/teacher-sessions", destination: `${attendanceUrl}/api/teacher-sessions` },
      { source: "/api/teacher-sessions/:path*", destination: `${attendanceUrl}/api/teacher-sessions/:path*` },
      { source: "/api/leaves", destination: `${attendanceUrl}/api/leaves` },
      { source: "/api/leaves/:path*", destination: `${attendanceUrl}/api/leaves/:path*` },
      { source: "/api/leave", destination: `${attendanceUrl}/api/leaves` },
      { source: "/api/leave/:path*", destination: `${attendanceUrl}/api/leaves/:path*` },
      { source: "/api/leave-balance", destination: `${attendanceUrl}/api/leave-balance` },
      { source: "/api/leave-balance/:path*", destination: `${attendanceUrl}/api/leave-balance/:path*` },
      { source: "/api/leave-requests", destination: `${attendanceUrl}/api/leave-requests` },
      { source: "/api/leave-requests/:path*", destination: `${attendanceUrl}/api/leave-requests/:path*` },
      { source: "/api/teacher-staff-leave", destination: `${attendanceUrl}/api/leaves` },
      { source: "/api/teacher-staff-leave/:path*", destination: `${attendanceUrl}/api/leaves/:path*` },
      // Additional Attendance routes
      { source: "/api/attendance-exceptions", destination: `${attendanceUrl}/api/attendance-exceptions` },
      { source: "/api/attendance-exceptions/:path*", destination: `${attendanceUrl}/api/attendance-exceptions/:path*` },
      { source: "/api/leave-balance-accruals", destination: `${attendanceUrl}/api/leave-balance-accruals` },
      { source: "/api/leave-balance-accruals/:path*", destination: `${attendanceUrl}/api/leave-balance-accruals/:path*` },

      // CRM / Connect
      { source: "/api/leads", destination: `${connectUrl}/api/leads` },
      { source: "/api/leads/:path*", destination: `${connectUrl}/api/leads/:path*` },
      { source: "/api/trial-sessions", destination: `${connectUrl}/api/trial-sessions` },
      { source: "/api/trial-sessions/:path*", destination: `${connectUrl}/api/trial-sessions/:path*` },
      { source: "/api/messaging", destination: `${connectUrl}/api/messaging` },
      { source: "/api/messaging/:path*", destination: `${connectUrl}/api/messaging/:path*` },
      { source: "/api/deals", destination: `${connectUrl}/api/deals` },
      { source: "/api/deals/:path*", destination: `${connectUrl}/api/deals/:path*` },
      { source: "/api/marketing-campaigns", destination: `${socialMediaUrl}/api/marketing-campaigns` },
      { source: "/api/marketing-campaigns/:path*", destination: `${connectUrl}/api/marketing-campaigns/:path*` },
      { source: "/api/marketing-config", destination: `${connectUrl}/api/marketing-config` },
      { source: "/api/marketing-config/:path*", destination: `${connectUrl}/api/marketing-config/:path*` },
      { source: "/api/social/posts", destination: `${socialMediaUrl}/api/social-media/posts` },
      { source: "/api/social/posts/:path*", destination: `${socialMediaUrl}/api/social-media/posts/:path*` },
      { source: "/api/social/events", destination: `${socialMediaUrl}/api/social-media/events` },
      { source: "/api/social/events/:path*", destination: `${socialMediaUrl}/api/social-media/events/:path*` },
      { source: "/api/social-media-posts", destination: `${socialMediaUrl}/api/social-media-posts` },
      { source: "/api/social-media-posts/:path*", destination: `${socialMediaUrl}/api/social-media-posts/:path*` },
      { source: "/api/social-platforms", destination: `${socialMediaUrl}/api/social-platforms` },
      { source: "/api/social-platforms/:path*", destination: `${socialMediaUrl}/api/social-platforms/:path*` },
      { source: "/api/social-analytics", destination: `${socialMediaUrl}/api/social-analytics` },
      { source: "/api/social-analytics/:path*", destination: `${socialMediaUrl}/api/social-analytics/:path*` },
      { source: "/api/broadcasts", destination: `${connectUrl}/api/broadcasts` },
      { source: "/api/broadcasts/:path*", destination: `${connectUrl}/api/broadcasts/:path*` },
      { source: "/api/notifications", destination: `${connectUrl}/api/notifications` },
      { source: "/api/notifications/:path*", destination: `${connectUrl}/api/notifications/:path*` },
      // Native push routing — Capacitor / FCM / APNs token registration
      { source: "/api/device-tokens", destination: `${connectUrl}/api/device-tokens` },
      { source: "/api/device-tokens/:path*", destination: `${connectUrl}/api/device-tokens/:path*` },
      { source: "/api/messages", destination: `${connectUrl}/api/messages` },
      { source: "/api/messages/:path*", destination: `${connectUrl}/api/messages/:path*` },
      { source: "/api/tasks", destination: `${connectUrl}/api/tasks` },
      { source: "/api/tasks/:path*", destination: `${connectUrl}/api/tasks/:path*` },
      { source: "/api/documents", destination: `${connectUrl}/api/documents` },
      { source: "/api/documents/:path*", destination: `${connectUrl}/api/documents/:path*` },
      { source: "/api/activities", destination: `${connectUrl}/api/activities` },
      { source: "/api/activities/:path*", destination: `${connectUrl}/api/activities/:path*` },
      { source: "/api/chat", destination: `${connectUrl}/api/chat` },
      { source: "/api/chat/:path*", destination: `${connectUrl}/api/chat/:path*` },
      { source: "/api/groups", destination: `${connectUrl}/api/groups` },
      { source: "/api/groups/:path*", destination: `${connectUrl}/api/groups/:path*` },
      { source: "/api/attachments", destination: `${connectUrl}/api/attachments` },
      { source: "/api/attachments/:path*", destination: `${connectUrl}/api/attachments/:path*` },
      { source: "/api/calls", destination: `${connectUrl}/api/calls` },
      { source: "/api/calls/:path*", destination: `${connectUrl}/api/calls/:path*` },
      { source: "/api/reactions", destination: `${connectUrl}/api/reactions` },
      { source: "/api/reactions/:path*", destination: `${connectUrl}/api/reactions/:path*` },
      // Additional Connect routes
      { source: "/api/polls", destination: `${connectUrl}/api/polls` },
      { source: "/api/polls/:path*", destination: `${connectUrl}/api/polls/:path*` },
      { source: "/api/stories", destination: `${connectUrl}/api/stories` },
      { source: "/api/stories/:path*", destination: `${connectUrl}/api/stories/:path*` },
      { source: "/api/meetings", destination: `${connectUrl}/api/meetings` },
      { source: "/api/meetings/:path*", destination: `${connectUrl}/api/meetings/:path*` },
      { source: "/api/followups", destination: `${connectUrl}/api/followups` },
      { source: "/api/followups/:path*", destination: `${connectUrl}/api/followups/:path*` },
      { source: "/api/follow-ups", destination: `${connectUrl}/api/followups` },
      { source: "/api/follow-ups/:path*", destination: `${connectUrl}/api/followups/:path*` },
      { source: "/api/lead-notes", destination: `${connectUrl}/api/lead-notes` },
      { source: "/api/lead-notes/:path*", destination: `${connectUrl}/api/lead-notes/:path*` },
      { source: "/api/lead-activities", destination: `${connectUrl}/api/lead-activities` },
      { source: "/api/lead-activities/:path*", destination: `${connectUrl}/api/lead-activities/:path*` },
      { source: "/api/lead-tags", destination: `${connectUrl}/api/lead-tags` },
      { source: "/api/lead-tags/:path*", destination: `${connectUrl}/api/lead-tags/:path*` },
      { source: "/api/lead-status", destination: `${connectUrl}/api/lead-status` },
      { source: "/api/lead-status/:path*", destination: `${connectUrl}/api/lead-status/:path*` },
      { source: "/api/ai-tutor", destination: `${connectUrl}/api/ai-tutor` },
      { source: "/api/ai-tutor/:path*", destination: `${connectUrl}/api/ai-tutor/:path*` },
      { source: "/api/content-moderation", destination: `${connectUrl}/api/content-moderation` },
      { source: "/api/content-moderation/:path*", destination: `${connectUrl}/api/content-moderation/:path*` },
      { source: "/api/parent-teacher-meetings", destination: `${connectUrl}/api/parent-teacher-meetings` },
      { source: "/api/parent-teacher-meetings/:path*", destination: `${connectUrl}/api/parent-teacher-meetings/:path*` },
      { source: "/api/ad-accounts", destination: `${socialMediaUrl}/api/ad-accounts` },
      { source: "/api/ad-accounts/:path*", destination: `${socialMediaUrl}/api/ad-accounts/:path*` },
      { source: "/api/email-logs", destination: `${connectUrl}/api/email-logs` },
      { source: "/api/email-logs/:path*", destination: `${connectUrl}/api/email-logs/:path*` },
      { source: "/api/call-logs", destination: `${connectUrl}/api/call-logs` },
      { source: "/api/call-logs/:path*", destination: `${connectUrl}/api/call-logs/:path*` },
      { source: "/api/crm-automation", destination: `${connectUrl}/api/crm-automation` },
      { source: "/api/crm-automation/:path*", destination: `${connectUrl}/api/crm-automation/:path*` },
      { source: "/api/class-group-chat", destination: `${connectUrl}/api/class-group-chat` },
      { source: "/api/class-group-chat/:path*", destination: `${connectUrl}/api/class-group-chat/:path*` },
      // Additional Connect routes - Lead Management
      { source: "/api/lead-statuses", destination: `${connectUrl}/api/lead-statuses` },
      { source: "/api/lead-statuses/:path*", destination: `${connectUrl}/api/lead-statuses/:path*` },
      { source: "/api/lead-assignments", destination: `${connectUrl}/api/lead-assignments` },
      { source: "/api/lead-assignments/:path*", destination: `${connectUrl}/api/lead-assignments/:path*` },
      { source: "/api/lead-notes", destination: `${connectUrl}/api/lead-notes` },
      { source: "/api/lead-notes/:path*", destination: `${connectUrl}/api/lead-notes/:path*` },
      { source: "/api/campaign-leads", destination: `${connectUrl}/api/campaign-leads` },
      { source: "/api/campaign-leads/:path*", destination: `${connectUrl}/api/campaign-leads/:path*` },
      // Additional Connect routes - CRM Automation
      { source: "/api/crm-triggers", destination: `${connectUrl}/api/crm-triggers` },
      { source: "/api/crm-triggers/:path*", destination: `${connectUrl}/api/crm-triggers/:path*` },
      { source: "/api/crm-automations", destination: `${connectUrl}/api/crm-automations` },
      { source: "/api/crm-automations/:path*", destination: `${connectUrl}/api/crm-automations/:path*` },
      // Additional Connect routes - Chat Extended
      { source: "/api/chat/polls", destination: `${connectUrl}/api/chat/polls` },
      { source: "/api/chat/polls/:path*", destination: `${connectUrl}/api/chat/polls/:path*` },
      { source: "/api/chat/reactions", destination: `${connectUrl}/api/chat/reactions` },
      { source: "/api/chat/reactions/:path*", destination: `${connectUrl}/api/chat/reactions/:path*` },
      { source: "/api/chat/ai-tutor", destination: `${connectUrl}/api/chat/ai-tutor` },
      { source: "/api/chat/ai-tutor/:path*", destination: `${connectUrl}/api/chat/ai-tutor/:path*` },
      { source: "/api/chat/meetings", destination: `${connectUrl}/api/chat/meetings` },
      { source: "/api/chat/meetings/:path*", destination: `${connectUrl}/api/chat/meetings/:path*` },
      { source: "/api/chat/class-groups", destination: `${connectUrl}/api/chat/class-groups` },
      { source: "/api/chat/class-groups/:path*", destination: `${connectUrl}/api/chat/class-groups/:path*` },
      { source: "/api/chat/conversations", destination: `${connectUrl}/api/chat/conversations` },
      { source: "/api/chat/conversations/:path*", destination: `${connectUrl}/api/chat/conversations/:path*` },
      { source: "/api/chat/users", destination: `${connectUrl}/api/chat/users` },
      { source: "/api/chat/users/:path*", destination: `${connectUrl}/api/chat/users/:path*` },
      { source: "/api/chat/assignments", destination: `${connectUrl}/api/chat/assignments` },
      { source: "/api/chat/assignments/:path*", destination: `${connectUrl}/api/chat/assignments/:path*` },
      { source: "/api/chat/moderation", destination: `${connectUrl}/api/chat/moderation` },
      { source: "/api/chat/moderation/:path*", destination: `${connectUrl}/api/chat/moderation/:path*` },
      // Additional Connect routes - Content Moderation
      { source: "/api/content-moderation-rules", destination: `${connectUrl}/api/content-moderation-rules` },
      { source: "/api/content-moderation-rules/:path*", destination: `${connectUrl}/api/content-moderation-rules/:path*` },

      // Payroll
      { source: "/api/payroll", destination: `${payrollUrl}/api/payroll` },
      { source: "/api/payroll/:path*", destination: `${payrollUrl}/api/payroll/:path*` },
      { source: "/api/salary-config", destination: `${payrollUrl}/api/salary-config` },
      { source: "/api/salary-config/:path*", destination: `${payrollUrl}/api/salary-config/:path*` },
      { source: "/api/teacher-salaries", destination: `${payrollUrl}/api/teacher-salaries` },
      { source: "/api/teacher-salaries/:path*", destination: `${payrollUrl}/api/teacher-salaries/:path*` },
      { source: "/api/salaries", destination: `${payrollUrl}/api/salaries` },
      { source: "/api/salaries/:path*", destination: `${payrollUrl}/api/salaries/:path*` },
      // Additional Payroll routes
      // Aliases — the BonusController/DeductionController in payroll_service
      // are mounted at /api/payroll/bonuses and /api/payroll/deductions.
      // Keep the shorter aliases working for any caller that uses them.
      { source: "/api/bonuses", destination: `${payrollUrl}/api/payroll/bonuses` },
      { source: "/api/bonuses/:path*", destination: `${payrollUrl}/api/payroll/bonuses/:path*` },
      { source: "/api/deductions", destination: `${payrollUrl}/api/payroll/deductions` },
      { source: "/api/deductions/:path*", destination: `${payrollUrl}/api/payroll/deductions/:path*` },
      { source: "/api/tax-settings", destination: `${payrollUrl}/api/tax-settings` },
      { source: "/api/tax-settings/:path*", destination: `${payrollUrl}/api/tax-settings/:path*` },
      { source: "/api/salary-components", destination: `${payrollUrl}/api/salary-components` },
      { source: "/api/salary-components/:path*", destination: `${payrollUrl}/api/salary-components/:path*` },
      { source: "/api/payroll-cycles", destination: `${payrollUrl}/api/payroll-cycles` },
      { source: "/api/payroll-cycles/:path*", destination: `${payrollUrl}/api/payroll-cycles/:path*` },
      { source: "/api/salary-payouts", destination: `${payrollUrl}/api/salary-payouts` },
      { source: "/api/salary-payouts/:path*", destination: `${payrollUrl}/api/salary-payouts/:path*` },
      { source: "/api/teacher-overtime", destination: `${payrollUrl}/api/teacher-overtime` },
      { source: "/api/teacher-overtime/:path*", destination: `${payrollUrl}/api/teacher-overtime/:path*` },
      { source: "/api/payroll-records", destination: `${payrollUrl}/api/payroll-records` },
      { source: "/api/payroll-records/:path*", destination: `${payrollUrl}/api/payroll-records/:path*` },

      // AI Gateway
      { source: "/api/ai", destination: `${aiGatewayUrl}/api/ai` },
      { source: "/api/ai/:path*", destination: `${aiGatewayUrl}/api/ai/:path*` },
      { source: "/api/tutor", destination: `${aiGatewayUrl}/api/tutor` },
      { source: "/api/tutor/:path*", destination: `${aiGatewayUrl}/api/tutor/:path*` },

      // Rule Engine
      { source: "/api/rules", destination: `${ruleEngineUrl}/api/rules` },
      { source: "/api/rules/:path*", destination: `${ruleEngineUrl}/api/rules/:path*` },

      // Social Media Service
      { source: "/api/social-media", destination: `${socialMediaUrl}/api/social-media` },
      { source: "/api/social-media/:path*", destination: `${socialMediaUrl}/api/social-media/:path*` },
      // Additional Social Media routes (unique endpoints not in connect_service)
      { source: "/api/lead-followups", destination: `${socialMediaUrl}/api/lead-followups` },
      { source: "/api/lead-followups/:path*", destination: `${socialMediaUrl}/api/lead-followups/:path*` },
      { source: "/api/ad-campaigns", destination: `${socialMediaUrl}/api/ad-campaigns` },
      { source: "/api/ad-campaigns/:path*", destination: `${socialMediaUrl}/api/ad-campaigns/:path*` },
      { source: "/api/content-templates", destination: `${socialMediaUrl}/api/content-templates` },
      { source: "/api/content-templates/:path*", destination: `${socialMediaUrl}/api/content-templates/:path*` },
      { source: "/api/hashtag-groups", destination: `${socialMediaUrl}/api/hashtag-groups` },
      { source: "/api/hashtag-groups/:path*", destination: `${socialMediaUrl}/api/hashtag-groups/:path*` },
    ];
  },
};

module.exports = {
  reactStrictMode: true,
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
        port: '',
        pathname: '/**',
      },
    ],
  },
  // Security headers for all pages
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'X-Frame-Options', value: 'DENY' },
          { key: 'X-XSS-Protection', value: '1; mode=block' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=()' },
        ],
      },
    ];
  },
  ...withRewrites,
};
