server:
  port: 8082

spring:
  application:
    name: academy_service

  datasource:
    url: jdbc:postgresql://localhost:5432/lera
    username: lera
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
