"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "EN" | "VI";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Comprehensive translations
export const translations = {
  EN: {
    // Navigation
    home: "Home",
    courses: "Courses",
    about: "About",
    centers: "Centers",
    contact: "Contact",
    login: "Login",
    
    // Hero Section
    promo: "🎉 30% OFF for new students",
    heroTitle: "Unlock Your Future with",
    heroSubtitle: "Elevate English for Kids & Adults",
    heroDesc: "Personalized English learning with AI tutors, native teachers, real-time feedback, and gamified progress tracking.",
    registerCta: "Register for Free Consultation →",
    callNow: "Call Now",
    students: "10,000+ students",
    teachers: "50+ native teachers",
    satisfaction: "98% satisfaction",
    
    // Promo Timer
    promoTitle: "GET NOW",
    promoSubtitle: "1 MONTH FREE TRIAL",
    promoUrgent: "Limited time offer!",
    days: "Days",
    timerHours: "Hours",
    minutes: "Minutes",
    seconds: "Seconds",
    
    // Registration Form
    formTitle: "Register for Free Consultation",
    formSubtitle: "Get personalized learning path for your child",
    parentName: "Parent's Full Name *",
    childName: "Child's Name *",
    childAge: "Child's Age *",
    phone: "Phone Number *",
    email: "Email",
    selectAge: "Select age",
    submit: "Get Free Consultation",
    submitting: "Submitting...",
    successTitle: "Registration Successful!",
    successMsg: "We will contact you within 24 hours",
    terms: "By registering, you agree to our Terms of Service",
    
    // Features Section
    whyChoose: "Why Choose",
    whyChooseDesc: "Modern learning methods combining AI technology and native teachers",
    nativeTeachers: "Native Teachers",
    nativeTeachersDesc: "100% teachers from USA, UK, Australia with international TESOL/CELTA certificates",
    aiTutor: "AI Tutor 24/7",
    aiTutorDesc: "Smart AI assistant for practice anytime, real-time pronunciation assessment",
    gamified: "Gamified Learning",
    gamifiedDesc: "Learn through games, earn points, get badges - making learning fun",
    realtime: "Real-time Assessment",
    realtimeDesc: "Detailed learning progress tracking, weekly reports for parents",
    flexible: "Flexible Schedule",
    flexibleDesc: "Choose your preferred time, learn online or offline at centers",
    familyDiscount: "Family Discount",
    familyDiscountDesc: "20% off for 2nd child, 30% off for 3rd child - Learning together is more fun",
    
    // Learning Path Section
    learningPath: "Choose Your English Learning Path",
    learningPathDesc: "Cambridge standard curriculum for your child!",
    
    // Courses Section
    programs: "Programs",
    programsDesc: "Learning paths suitable for all ages",
    popular: "Popular",
    hot: "Hot",
    premium: "Premium",
    ages: "years old",
    adults: "Working Adults",
    viewDetails: "View Details →",
    viewAllCourses: "View All Courses",
    
    // Course Names
    startersTitle: "LERA Starters",
    startersDesc: "Introduction to English through songs, games, and interactive activities",
    startersFeatures: "Focus on Listening - Speaking skills\nNative pronunciation\nSimple vocabulary about daily life",
    speakingTitle: "LERA Speaking Pro",
    speakingDesc: "Develop communication skills, speak English confidently like a native",
    speakingFeatures: "Master 4 skills: Listening - Speaking - Reading - Writing\nCambridge standard foundation\nPresentation and critical thinking skills",
    teensTitle: "LERA Teens",
    teensDesc: "Advanced grammar, academic vocabulary, preparation for international exams",
    teensFeatures: "Advanced academic English\nInternational certificates (KET, PET, IELTS)\n21st century soft skills development",
    ieltsTitle: "LERA IELTS Master",
    ieltsDesc: "Intensive IELTS preparation, guaranteed band 6.5-8.0",
    satTitle: "LERA SAT Prep",
    satDesc: "Prepare for US study abroad with professional SAT prep course",
    businessTitle: "Business English",
    businessDesc: "Business English, office communication, professional presentations",
    
    // Achievements Section
    achievementsTitle: "Outstanding Students Leading The Future",
    achievementsDesc: "LERA Academy is proud to accompany students on their journey to conquer international standard English",
    certificateAchieved: "achieved",
    
    // Teachers Section
    teachersTitle: "Elite International Standard Teaching Team",
    teachersDesc: "All teachers from English-speaking countries with international certificates like CELTA, TESOL, TEFL",
    teacherCount: "50+ Native Teachers",
    
    // Classroom Section
    classroomTitle: "Nurturing Learning Inspiration",
    classroomSubtitle: "International Standard English Classroom",
    classroomDesc: "Focus on student health and learning experience with minimalist design, high-quality equipment safe for all ages",
    
    // Testimonials
    testimonialTitle: "What Parents Say About Us?",
    testimonialDesc: "Thousands of families trust LERA Academy",
    testimonial1: "My child went from being afraid of English to confidently communicating with foreigners. Thank you LERA!",
    parent1: "Ms. Minh Anh",
    child1: "Parent of Gia Han, 8 years old",
    testimonial2: "The gamified learning method makes my child enjoy learning more. Every day wants to learn English.",
    parent2: "Mr. James P.",
    child2: "Parent of Ethan, 10 years old",
    testimonial3: "My child achieved IELTS 7.5 after 8 months at LERA. Teachers are dedicated and professional.",
    parent3: "Ms. Sophia M.",
    child3: "Parent of Linh, 17 years old",
    
    // Stats
    studentsCount: "10,000+",
    studentsLabel: "Students",
    teachersCount: "50+",
    teachersLabel: "Native Teachers",
    centersCount: "5+",
    centersLabel: "Learning Centers",
    satisfactionCount: "98%",
    satisfactionLabel: "Satisfaction Rate",
    
    // Social
    followUs: "Follow Us",
    followUsDesc: "Stay updated with latest news and activities from LERA",
    facebook: "Facebook",
    instagram: "Instagram",
    tiktok: "TikTok",
    followNow: "Follow Now →",
    watchVideos: "Watch Videos →",
    
    // CTA
    ctaTitle: "Ready to Start Your Journey?",
    ctaDesc: "Register now for a free trial lesson and personalized learning path",
    
    // Floating CTA
    floatingCta: "1 MONTH FREE TRIAL",
    scholarshipThisMonth: "Scholarship this month",
    exploreClass: "Explore classes",
    teacherQuality: "Teacher quality",
    
    // Footer
    footerDesc: "Leading English center with modern learning methods combining AI and native teachers.",
    pages: "Pages",
    coursesFooter: "Courses",
    contactFooter: "Contact",
    address: "95 Hai Dang, Vinhomes Marina, An Bien Ward, Hai Phong",
    workingHours: "8:00 AM - 9:00 PM (Mon - Sun)",
    privacy: "Privacy Policy",
    termsFooter: "Terms of Service",
    allRightsReserved: "All rights reserved",
    
    // About Page
    aboutHeroTitle: "About LERA Academy",
    aboutHeroDesc: "Empowering learners with English skills for global success",
    ourStory: "Our Story",
    ourStoryDesc: "Founded in 2020, LERA Academy has been dedicated to providing high-quality English education combining modern AI technology with experienced native teachers.",
    ourMission: "Our Mission",
    ourMissionDesc: "To make English learning accessible, engaging, and effective for learners of all ages through innovative teaching methods.",
    ourVision: "Our Vision",
    ourVisionDesc: "To become the leading English education center in Vietnam, nurturing confident global citizens.",
    leadership: "Leadership Team",
    
    // Contact Page
    contactHeroTitle: "Contact Us",
    contactHeroDesc: "We'd love to hear from you",
    getInTouch: "Get In Touch",
    sendMessage: "Send Message",
    yourName: "Your Name",
    yourEmail: "Your Email",
    subject: "Subject",
    message: "Message",
    
    // Centers Page
    centersHeroTitle: "Our Learning Centers",
    centersHeroDesc: "Find a center near you",
    
    // Courses Page
    coursesHeroTitle: "Our Courses",
    coursesHeroDesc: "Find the perfect course for you",
    allCourses: "All Courses",
    filterBy: "Filter by",
    registerNow: "Register Now",
    
    // Course Detail Page
    backToCourses: "← Back to Courses",
    ageGroup: "Age Group",
    yearsOld: "years old",
    courseDuration: "Duration",
    weeks: "weeks",
    courseSchedule: "Schedule",
    sessionsWeek: "sessions/week",
    classSize: "Class Size",
    classSizeStudents: "students",
    courseLevel: "Level",
    curriculum: "Curriculum",
    whyThisCourse: "Why Choose This Course",
    registerForCourse: "Register for This Course",
    regSuccessTitle: "Thank You!",
    regSuccessMsg: "We will contact you within 24 hours to confirm your enrollment.",
    otherCourses: "Other Courses",
    formName: "Your Name",
    formPhone: "Phone Number",
    formEmail: "Email",
    formChild: "Child's Name",
    formAge: "Age",
    submitReg: "Submit Registration",
    submittingReg: "Submitting...",
    
    // Homepage additional translations
    limitedOffer: "Limited Time Offer - 30% OFF",
    freeConsult: "Free Consultation",
    hotDeal: "HOT DEAL",
    freeTrialClass: "Free Trial Class",
    tryBeforeEnroll: "Try before you enroll",
    noPaymentRequired: "No payment required",
    happyStudents: "Happy Students",
    yearsExperience: "Years Experience",
    studentsEnrolled: "Students Enrolled",
    expertTeachers: "Expert Teachers",
    learningCenters: "Learning Centers",
    learningPathTitle: "Choose Your Learning Path",
    learningPathSubtitle: "Personalized curriculum for every age group",
    pathKids: "LERA Kids",
    pathKidsDesc: "Fun and interactive English for young learners",
    pathJunior: "LERA Junior",
    pathJuniorDesc: "Build strong foundation with Cambridge curriculum",
    pathTeen: "LERA Teens",
    pathTeenDesc: "Academic English & exam preparation",
    agesLabel: "Ages",
    learnMore: "Learn More",
    whyChooseUs: "Why Choose LERA Academy",
    modernMethod: "Modern Methods",
    modernMethodDesc: "Combining AI technology with proven teaching techniques",
    smallClass: "Small Class Size",
    smallClassDesc: "Maximum 12 students per class for personalized attention",
    intlCertificate: "International Certificates",
    intlCertificateDesc: "Prepare students for Cambridge, IELTS, TOEFL exams",
    meetTeachers: "Meet Our Teachers",
    teachersSubtitle: "Experienced native speakers from English-speaking countries",
    experience: "experience",
    parentsSay: "What Parents Say",
    parentOf: "Parent of",
    viewCourses: "View Courses",
    contactUs: "Contact Us",
    
    // ===== DASHBOARD TRANSLATIONS =====
    // Dashboard Navigation
    dashboard: "Dashboard",
    welcomeBack: "Welcome back! Here's what's happening at LERA Academy.",
    
    // Chairman Panel
    chairmanPanel: "Chairman Panel",
    controlCenter: "Control Center",
    userManagement: "User Management",
    staffManagement: "Staff (Teachers/Parents/Admins)",
    boardOfDirectors: "Board of Directors",
    directors: "Directors",
    orgStructure: "Org Structure & Reporting",
    rolesPermissions: "Roles & Permissions",
    departments: "Departments",
    excelDataImport: "Excel Data Import",
    systemSettings: "System Settings",
    dropdownOptions: "Dropdown Options",
    pendingApprovals: "Pending Approvals",
    auditLogs: "Audit Logs",
    
    // Organization
    organization: "Organization",
    allCenters: "All Centers",
    addNewCenter: "Add New Center",
    centerAnalytics: "Center Analytics",
    dataImport: "Data Import",
    
    // Public Website
    publicWebsite: "Public Website",
    homePageEditor: "Home Page Editor",
    heroSection: "Hero Section",
    websiteSettings: "Website Settings",
    coursesSection: "Courses Section",
    aboutPage: "About Page",
    contactPage: "Contact Page",
    centersPage: "Centers Page",
    testimonials: "Testimonials",
    blogPosts: "Blog & Posts",
    faqManagement: "FAQ Management",
    branding: "Branding",
    footer: "Footer",
    seoSettings: "SEO Settings",
    
    // Academy
    academy: "Academy",
    studentsNav: "Students",
    teachersNav: "Teachers",
    coursesNav: "Courses",
    classes: "Classes",
    classrooms: "Classrooms",
    enrollments: "Enrollments",
    
    // Attendance & Leave
    attendanceLeave: "Attendance & Leave",
    myAttendance: "My Attendance",
    myLeaveRequests: "My Leave Requests",
    leaveApprovals: "Leave Approvals",
    approvals: "Approvals",
    overview: "Overview",
    studentAttendance: "Student Attendance",
    teacherAttendance: "Teacher Attendance",
    userAttendance: "User Attendance",
    
    // Exams & Progress
    examsProgress: "Exams & Progress",
    mySchedule: "My Schedule",
    myGrades: "My Grades",
    taGrades: "TA Grades",
    exams: "Exams",
    results: "Results",
    progressReports: "Progress Reports",
    
    // Finance
    finance: "Finance",
    financeDashboard: "Finance Dashboard",
    payments: "Payments",
    invoices: "Invoices",
    studentFeeManagement: "Student Fee Management",
    feePlans: "Fee Plans",
    feeRules: "Fee Rules",
    discounts: "Discounts",
    refunds: "Refunds",
    payroll: "Payroll",
    reports: "Reports",
    
    // CRM
    crm: "CRM",
    leads: "Leads",
    followUps: "Follow-ups",
    registrations: "Registrations",
    
    // Parent Communications
    parentCommunications: "Parent Communications",
    
    // LERA Connect
    leraConnect: "LERA Connect",
    
    // AI & Analytics
    aiAnalytics: "AI & Analytics",
    aiGateway: "AI Gateway",
    gamification: "Gamification",
    
    // Student Panel
    myClasses: "My Classes",
    assignments: "Assignments",
    grades: "Grades",
    attendance: "Attendance",
    messages: "Messages",
    myProfile: "My Profile",
    
    // Parent Panel
    children: "Children",
    schedule: "Schedule",
    communication: "Communication",
    
    // TA Panel
    gradesAssessment: "Grades & Assessment",
    tasks: "Tasks",
    
    // Dashboard Stats
    totalStudents: "Total Students",
    totalTeachers: "Total Teachers",
    totalCenters: "Total Centers",
    monthlyRevenue: "Monthly Revenue",
    activeClasses: "Active Classes",
    attendanceRate: "Attendance Rate",
    superadminQuickActions: "SuperAdmin Quick Actions",
    editHomepage: "Edit Homepage",
    editCourses: "Edit Courses",
    recentActivities: "Recent Activities",
    viewAll: "View All",
    pendingLeads: "Pending Leads",
    awaitingFollowup: "Awaiting Follow-up",
    converted: "Converted",
    newLeads: "New Leads",
    centerPerformance: "Center Performance",
    welcomeBackAdmin: "Welcome back, Administrator",
    viewWebsite: "View Website",
    quickLinks: "Quick Links",
    manageCenters: "Manage all centers",
    manageHomepage: "Edit homepage",
    manageCourses: "Manage courses",
    manageBlog: "Manage blog",
    manageTestimonials: "Manage reviews",
    brandSettings: "Brand settings",
    centersManagement: "Centers Management",
    
    // Common Actions
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    search: "Search",
    filter: "Filter",
    export: "Export",
    import: "Import",
    refresh: "Refresh",
    loading: "Loading...",
    noData: "No data available",
    actions: "Actions",
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    completed: "Completed",
    
    // Time
    today: "Today",
    week: "Week",
    month: "Month",
    year: "Year",
    
    // Profile
    profile: "Profile",
    settings: "Settings",
    logout: "Logout",
    notifications: "Notifications",
    markAllRead: "Mark all as read",
    noNotifications: "No notifications",
    viewAllNotifications: "View all notifications",
    
    // Errors & Messages
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Info",
    confirmDelete: "Are you sure you want to delete this item?",
    deleteSuccess: "Deleted successfully",
    saveSuccess: "Saved successfully",
    updateSuccess: "Updated successfully",
    
    // Marketing
    socialMediaPosts: "Social Media Posts",
    marketingCampaigns: "Marketing Campaigns",
    socialAnalytics: "Social Analytics",
    platforms: "Platforms",
    reach: "Reach",
    likes: "Likes",
    shares: "Shares",
    comments: "Comments",
    followers: "Followers",
    engagementRate: "Engagement Rate",
    scheduled: "Scheduled",
    published: "Published",
    draft: "Draft",
    
    // Role-specific Dashboard Labels
    directorDashboard: "Director Dashboard",
    strategicOverview: "Strategic overview of all operations",
    totalStaff: "Total Staff",
    totalRevenue: "Total Revenue",
    quickActions: "Quick Actions",
    ceoDashboard: "CEO Dashboard",
    executiveOverview: "Executive overview of the organization",
    growthRate: "Growth Rate",
    financialReports: "Financial Reports",
    strategicPlans: "Strategic Plans",
    analytics: "Analytics",
    staffDashboard: "Staff Dashboard",
    welcomeStaff: "Welcome",
    tasksToday: "Tasks Today",
    taDashboard: "Teaching Assistant Dashboard",
    welcomeTA: "Welcome",
    assignedClasses: "Assigned Classes",
    studentsHelping: "Students Helping",
    todaySessions: "Today's Sessions",
    teacherDashboard: "Teacher Dashboard",
    welcomeTeacher: "Welcome back",
    myStudents: "My Students",
    pendingAttendance: "Pending Attendance",
    takeAttendance: "Take Attendance",
    studentList: "Student List",
    todaysSchedule: "Today's Schedule",
    room: "Room",
    studentsDash: "students",
    inProgress: "In Progress",
    upcoming: "Upcoming",
    studentDashboard: "Student Dashboard",
    welcomeStudent: "Welcome back",
    myCourses: "My Courses",
    upcomingClasses: "Upcoming Classes",
    assignmentsDue: "Assignments Due",
    parentDashboard: "Parent Dashboard",
    monitorProgress: "Monitor your children's progress",
    childrenProgress: "Children Progress",
    avgAttendance: "Avg Attendance",
    upcomingFees: "Upcoming Fees",
    centerAdminDashboard: "Center Admin Dashboard",
    manageCenter: "Manage your center operations",
    centerManagerDashboard: "Center Manager Dashboard",
    academicManagerDashboard: "Academic Manager Dashboard",
    myTasks: "My Tasks",
    myCalendar: "My Calendar",
    
    // Recent Activity
    recentActivity: "Recent Activity",
    noRecentActivity: "No recent activity",
    systemReady: "System is ready",
    paymentReceived: "Payment received",
    newStudent: "New student enrolled",
    newTeacher: "New teacher added",
    courseUpdated: "Course updated",
    newStudentRegistered: "New student registered",
    newUserRegistered: "New user registered",
    newEnrollment: "New enrollment",
    recentStudents: "Recent Students",
    noStudentsFound: "No students found",
    searchStudents: "Search students...",
    viewStudents: "View Students",
    created: "Created",
    recentPayments: "Recent Payments",
    
    // Login Page
    backToHome: "Back to Home",
    welcomeBackLogin: "Welcome Back",
    signInToAccount: "Sign in to your LERA Academy account",
    emailAddress: "Email Address",
    emailPlaceholder: "you@example.com",
    password: "Password",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    signIn: "Sign In",
    signingIn: "Signing in...",
    noAccount: "Don't have an account?",
    contactAdmin: "Contact Admin",

    // Finance Module (extended)
    financeOverview: "Comprehensive financial overview and analytics",
    totalRevenueLabel: "Total Revenue",
    outstandingBalance: "Outstanding Balance",
    refundedAmount: "Refunded Amount",
    collectionRate: "Collection Rate",
    studentsPaying: "Students Paying",
    overdueCount: "Overdue",
    invoiceCountLabel: "Invoices",
    generateManage: "Generate & manage",
    trackPayments: "Track payments",
    configureFees: "Configure fees",
    processRefunds: "Process refunds",
    manageDiscounts: "Manage discounts",
    studentPlans: "Student Plans",
    paymentPlans: "Payment plans",
    revenueByCenter: "Revenue by Center",
    recentTransactions: "Recent Transactions",
    monthlyTrend: "Monthly Trend",
    noTransactions: "No recent transactions",

    // Academy Module (extended)
    academyDashboard: "Academy Dashboard",
    academyOverview: "Academic management and overview",
    totalStudentsLabel: "Total Students",
    totalTeachersLabel: "Total Teachers",
    totalClassesLabel: "Total Classes",
    totalCoursesLabel: "Total Courses",
    activeEnrollments: "Active Enrollments",
    parents: "Parents",
    staffMembers: "Staff Members",
    manageStudents: "Manage Students",
    manageTeachers: "Manage Teachers",
    manageClasses: "Manage Classes",
    addNew: "Add New",
    confirm: "Confirm",
    close: "Close",
    all: "All",

    // Exams Module
    examsDashboard: "Exams & Assessments",
    examOverview: "Manage exams and student assessments",
    upcomingExams: "Upcoming Exams",
    examResults: "Exam Results",
    examProgress: "Progress Tracking",
    averageScore: "Average Score",
    passRate: "Pass Rate",
    totalExams: "Total Exams",
    createExam: "Create Exam",

    // Attendance Module (extended)
    attendanceDashboard: "Attendance Management",
    attendanceOverview: "Track and manage attendance records",
    presentToday: "Present Today",
    absentToday: "Absent Today",
    lateToday: "Late Today",
    attendanceRateLabel: "Attendance Rate",
    markAttendance: "Mark Attendance",
    viewAttendance: "View Attendance",
    attendanceHistory: "Attendance History",

    // CRM Module
    crmDashboard: "CRM Dashboard",
    crmOverview: "Lead management and conversions",
    totalLeads: "Total Leads",
    conversionRate: "Conversion Rate",
    leadsPipeline: "Leads Pipeline",
    communications: "Communications",
    automations: "Automations",
    tags: "Tags",

    // Reports Module
    reportsDashboard: "Reports & Analytics",
    generateReport: "Generate Report",
    downloadReport: "Download Report",
    revenueReport: "Revenue Report",
    performanceReport: "Performance Report",
    attendanceReport: "Attendance Report",
    enrollmentReport: "Enrollment Report",

    // Common Dashboard Labels
    manage: "Manage",
    configuration: "Configuration",
    thisWeek: "This Week",
    thisMonth: "This Month",
    lastMonth: "Last Month",
    dateRange: "Date Range",
    from: "From",
    to: "To",
    apply: "Apply",
    reset: "Reset",
    details: "Details",
    view: "View",
    back: "Back",
    next: "Next",
    previous: "Previous",
    showing: "Showing",
    of: "of",
    perPage: "per page",
    noResults: "No results found",
    searchPlaceholder: "Search...",
    sortBy: "Sort by",
    ascending: "Ascending",
    descending: "Descending",
    createdAt: "Created At",
    updatedAt: "Updated At",
    description: "Description",
    type: "Type",
    category: "Category",
    amount: "Amount",
    date: "Date",
    time: "Time",
    notes: "Notes",
    attachments: "Attachments",
    priority: "Priority",
    high: "High",
    medium: "Medium",
    low: "Low",
    approved: "Approved",
    rejected: "Rejected",
    inReview: "In Review",
    submitted: "Submitted",
    quarter: "Quarter",

    // Chairman Dashboard
    chairmanControlPanel: "Chairman Control Panel",
    fullAdminAccess: "Full administrative access to all system components",
    systemOverview: "System Overview",
    usersAndRoles: "Users & Roles",
    pendingApprovalsTab: "Pending Approvals",
    centersTab: "Centers",
    departmentsTab: "Departments",
    coursesAndPrograms: "Courses & Programs",
    marketingTab: "Marketing",
    websiteContent: "Website Content",
    totalUsers: "Total Users",
    pendingApprovalsCount: "Pending Approvals",
    addUser: "Add User",
    addCenter: "Add Center",
    reviewApprovals: "Review Approvals",
    systemRoles: "System Roles",
    usersRolesManagement: "Users & Roles Management",
    addNewUser: "+ Add New User",
    searchUsers: "Search users...",
    allCaughtUp: "All caught up!",
    noPendingApprovals: "No pending approvals at this time.",
    submittedBy: "Submitted by",
    approve: "Approve",
    reject: "Reject",
    noAddress: "No address",
    noPhone: "No phone",
    departmentsManagement: "Departments Management",
    addDepartment: "+ Add Department",
    department: "Department",
    code: "Code",
    addCourse: "+ Add Course",
    noDescription: "No description",
    allLevels: "All Levels",
    general: "General",
    addSetting: "+ Add Setting",
    key: "Key",
    value: "Value",
    public: "Public",
    yes: "Yes",
    no: "No",
    saveChanges: "Save Changes",
    user: "User",
    websiteContentManagement: "Website Content Management",
    managePublicContent: "Manage all public-facing website content",
    openContentManager: "Open Content Manager →",
    homePage: "Home Page",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    updatedSuccessfully: "Updated successfully!",
    failedToUpdate: "Failed to update. Please try again.",
    errorSaving: "Error saving changes.",
    deletedSuccessfully: "Deleted successfully!",
    failedToDelete: "Failed to delete.",

    // Reports
    viewDownloadReports: "View and download your reports",
    totalReports: "Total Reports",
    ready: "Ready",
    generating: "Generating",
    reportTypes: "Report Types",
    academic: "Academic",
    financial: "Financial",
    performance: "Performance",
    download: "Download",
    failed: "Failed",
    generateNewReport: "Generate New Report",
    reportType: "Report Type",
    academicReport: "Academic Report",
    financialReport: "Financial Report",
    format: "Format",
    generate: "Generate",
    noReportsFound: "No reports found",
    failedToDownload: "Failed to download report",

    // Connect / Messaging
    messaging: "Messaging",
    conversations: "Conversations",
    newMessage: "New Message",
    typeMessage: "Type a message...",
    send: "Send",
    online: "Online",
    offline: "Offline",
    noConversations: "No conversations yet",
  },
  VI: {
    // Navigation
    home: "Trang chủ",
    courses: "Khóa học",
    about: "Về chúng tôi",
    centers: "Cơ sở",
    contact: "Liên hệ",
    login: "Đăng nhập",
    
    // Hero Section
    promo: "🎉 Ưu đãi 30% cho học viên mới",
    heroTitle: "Mở Cánh Cửa Tương Lai Với",
    heroSubtitle: "Nâng Tầm Tiếng Anh Cho Trẻ Em & Người Lớn",
    heroDesc: "Học tiếng Anh cá nhân hóa với AI tutor, giáo viên bản ngữ, phản hồi real-time và gamified learning.",
    registerCta: "Đăng ký tư vấn miễn phí →",
    callNow: "Gọi ngay",
    students: "10,000+ học viên",
    teachers: "50+ giáo viên bản ngữ",
    satisfaction: "98% hài lòng",
    
    // Promo Timer
    promoTitle: "NHẬN NGAY",
    promoSubtitle: "1 THÁNG HỌC MIỄN PHÍ",
    promoUrgent: "Thời gian ưu đãi có hạn!",
    days: "Ngày",
    timerHours: "Giờ",
    minutes: "Phút",
    seconds: "Giây",
    
    // Registration Form
    formTitle: "Đăng ký tư vấn miễn phí",
    formSubtitle: "Nhận lộ trình học tập phù hợp cho bé",
    parentName: "Họ và tên phụ huynh *",
    childName: "Tên con *",
    childAge: "Tuổi của con *",
    phone: "Số điện thoại *",
    email: "Email",
    selectAge: "Chọn độ tuổi",
    submit: "Nhận tư vấn miễn phí",
    submitting: "Đang gửi...",
    successTitle: "Đăng ký thành công!",
    successMsg: "Chúng tôi sẽ liên hệ bạn trong 24h",
    terms: "Bằng việc đăng ký, bạn đồng ý với Điều khoản sử dụng của chúng tôi",
    
    // Features Section
    whyChoose: "Tại sao chọn",
    whyChooseDesc: "Phương pháp học tập hiện đại, kết hợp công nghệ AI và giáo viên bản ngữ",
    nativeTeachers: "Giáo viên bản ngữ",
    nativeTeachersDesc: "100% giáo viên đến từ Mỹ, Anh, Úc với chứng chỉ TESOL/CELTA quốc tế",
    aiTutor: "AI Tutor 24/7",
    aiTutorDesc: "Trợ lý AI thông minh hỗ trợ luyện tập mọi lúc, đánh giá phát âm real-time",
    gamified: "Gamified Learning",
    gamifiedDesc: "Học qua trò chơi, tích điểm, nhận huy hiệu - khiến việc học trở nên thú vị",
    realtime: "Đánh giá real-time",
    realtimeDesc: "Theo dõi tiến độ học tập chi tiết, báo cáo hàng tuần cho phụ huynh",
    flexible: "Lịch học linh hoạt",
    flexibleDesc: "Tự chọn thời gian học phù hợp, học online hoặc offline tại trung tâm",
    familyDiscount: "Ưu đãi gia đình",
    familyDiscountDesc: "Giảm 20% cho con thứ 2, 30% cho con thứ 3 - Học cùng gia đình vui hơn",
    
    // Learning Path Section
    learningPath: "Chọn Lộ Trình Chinh Phục Tiếng Anh",
    learningPathDesc: "Chuẩn Cambridge cho con bạn!",
    
    // Courses Section
    programs: "Chương trình học",
    programsDesc: "Lộ trình học tập phù hợp với mọi độ tuổi",
    popular: "Phổ biến",
    hot: "Hot",
    premium: "Cao cấp",
    ages: "tuổi",
    adults: "Người đi làm",
    viewDetails: "Xem chi tiết →",
    viewAllCourses: "Xem tất cả khóa học",
    
    // Course Names
    startersTitle: "LERA Starters",
    startersDesc: "Làm quen tiếng Anh qua bài hát, trò chơi và hoạt động tương tác",
    startersFeatures: "Tập trung phát triển kỹ năng Nghe - Nói\nPhát âm chuẩn ngữ điệu bản xứ\nTiếp cận từ vựng chủ đề đơn giản về cuộc sống",
    speakingTitle: "LERA Speaking Pro",
    speakingDesc: "Phát triển kỹ năng giao tiếp, tự tin nói tiếng Anh như người bản ngữ",
    speakingFeatures: "Hoàn thiện 4 kỹ năng Nghe - Nói - Đọc - Viết\nNền tảng Anh ngữ học thuật chuẩn Cambridge\nRèn kỹ năng thuyết trình, tư duy phản biện",
    teensTitle: "LERA Teens",
    teensDesc: "Nâng cao ngữ pháp, từ vựng học thuật, chuẩn bị cho các kỳ thi quốc tế",
    teensFeatures: "Tiếng Anh học thuật chuyên sâu\nChứng chỉ quốc tế (KET, PET, IELTS)\nPhát triển 6 kỹ năng mềm thế kỷ 21",
    ieltsTitle: "LERA IELTS Master",
    ieltsDesc: "Luyện thi IELTS chuyên sâu, cam kết đầu ra band 6.5-8.0",
    satTitle: "LERA SAT Prep",
    satDesc: "Chuẩn bị du học Mỹ với khóa luyện thi SAT chuyên nghiệp",
    businessTitle: "Business English",
    businessDesc: "Tiếng Anh thương mại, giao tiếp văn phòng, thuyết trình chuyên nghiệp",
    
    // Achievements Section
    achievementsTitle: "Thế Hệ Ưu Tú Dẫn Đầu Tương Lai",
    achievementsDesc: "LERA Academy tự hào đồng hành cùng các bé trên hành trình chinh phục tiếng Anh chuẩn quốc tế",
    certificateAchieved: "đạt",
    
    // Teachers Section
    teachersTitle: "Đội Ngũ Giáo Viên Tinh Hoa Chuẩn Quốc Tế",
    teachersDesc: "Tất cả giáo viên đến từ các quốc gia nói tiếng Anh với chứng chỉ quốc tế CELTA, TESOL, TEFL",
    teacherCount: "50+ Giáo Viên Bản Ngữ",
    
    // Classroom Section
    classroomTitle: "Nuôi Dưỡng Cảm Hứng Học Tập",
    classroomSubtitle: "Không Gian Lớp Tiếng Anh Chuẩn Quốc Tế",
    classroomDesc: "Chú trọng sức khỏe và trải nghiệm học tập với thiết kế tối giản, trang thiết bị chất lượng cao, an toàn cho từng độ tuổi",
    
    // Testimonials
    testimonialTitle: "Phụ huynh nói gì về chúng tôi?",
    testimonialDesc: "Hàng ngàn gia đình đã tin tưởng LERA Academy",
    testimonial1: "Con tôi từ sợ tiếng Anh giờ đã tự tin giao tiếp với người nước ngoài. Cảm ơn LERA rất nhiều!",
    parent1: "Chị Minh Anh",
    child1: "Phụ huynh bé Gia Hân, 8 tuổi",
    testimonial2: "Phương pháp học gamified giúp con tôi thích học hơn. Mỗi ngày đều muốn được học tiếng Anh.",
    parent2: "Anh James P.",
    child2: "Phụ huynh bé Ethan, 10 tuổi",
    testimonial3: "Con đạt IELTS 7.5 sau 8 tháng học tại LERA. Giáo viên rất tận tâm và chuyên nghiệp.",
    parent3: "Chị Sophia M.",
    child3: "Phụ huynh Linh, 17 tuổi",
    
    // Stats
    studentsCount: "10,000+",
    studentsLabel: "Học viên",
    teachersCount: "50+",
    teachersLabel: "Giáo viên bản ngữ",
    centersCount: "5+",
    centersLabel: "Cơ sở học tập",
    satisfactionCount: "98%",
    satisfactionLabel: "Tỷ lệ hài lòng",
    
    // Social
    followUs: "Theo dõi chúng tôi",
    followUsDesc: "Cập nhật tin tức và hoạt động mới nhất từ LERA",
    facebook: "Facebook",
    instagram: "Instagram",
    tiktok: "TikTok",
    followNow: "Theo dõi ngay →",
    watchVideos: "Xem video →",
    
    // CTA
    ctaTitle: "Sẵn sàng bắt đầu hành trình?",
    ctaDesc: "Đăng ký ngay để nhận buổi học thử miễn phí và lộ trình học tập cá nhân hóa",
    
    // Floating CTA
    floatingCta: "1 THÁNG HỌC THỬ MIỄN PHÍ",
    scholarshipThisMonth: "Học bổng trong tháng",
    exploreClass: "Khám phá lớp học",
    teacherQuality: "Chất lượng giáo viên",
    
    // Footer
    footerDesc: "Trung tâm Anh ngữ hàng đầu với phương pháp học hiện đại kết hợp AI và giáo viên bản ngữ.",
    pages: "Trang",
    coursesFooter: "Khóa học",
    contactFooter: "Liên hệ",
    address: "95 Hải Đăng, khu đô thị Vinhomes Marina, phường An Biên, Hải Phòng",
    workingHours: "8:00 - 21:00 (Thứ 2 - CN)",
    privacy: "Chính sách bảo mật",
    termsFooter: "Điều khoản sử dụng",
    allRightsReserved: "Bảo lưu mọi quyền",
    
    // About Page
    aboutHeroTitle: "Về LERA Academy",
    aboutHeroDesc: "Trang bị kỹ năng tiếng Anh cho thành công toàn cầu",
    ourStory: "Câu Chuyện Của Chúng Tôi",
    ourStoryDesc: "Thành lập năm 2020, LERA Academy cam kết mang đến nền giáo dục tiếng Anh chất lượng cao, kết hợp công nghệ AI hiện đại với đội ngũ giáo viên bản ngữ giàu kinh nghiệm.",
    ourMission: "Sứ Mệnh",
    ourMissionDesc: "Làm cho việc học tiếng Anh trở nên dễ tiếp cận, hấp dẫn và hiệu quả cho mọi lứa tuổi thông qua phương pháp giảng dạy sáng tạo.",
    ourVision: "Tầm Nhìn",
    ourVisionDesc: "Trở thành trung tâm giáo dục tiếng Anh hàng đầu Việt Nam, nuôi dưỡng công dân toàn cầu tự tin.",
    leadership: "Ban Lãnh Đạo",
    
    // Contact Page
    contactHeroTitle: "Liên Hệ Chúng Tôi",
    contactHeroDesc: "Chúng tôi muốn lắng nghe từ bạn",
    getInTouch: "Liên Hệ Ngay",
    sendMessage: "Gửi Tin Nhắn",
    yourName: "Họ và tên",
    yourEmail: "Email của bạn",
    subject: "Tiêu đề",
    message: "Nội dung",
    
    // Centers Page
    centersHeroTitle: "Các Cơ Sở Học Tập",
    centersHeroDesc: "Tìm cơ sở gần bạn",
    
    // Courses Page
    coursesHeroTitle: "Các Khóa Học",
    coursesHeroDesc: "Tìm khóa học phù hợp cho bạn",
    allCourses: "Tất cả khóa học",
    filterBy: "Lọc theo",
    registerNow: "Đăng Ký Ngay",
    
    // Course Detail Page
    backToCourses: "← Quay lại khóa học",
    ageGroup: "Độ tuổi",
    yearsOld: "tuổi",
    courseDuration: "Thời lượng",
    weeks: "tuần",
    courseSchedule: "Lịch học",
    sessionsWeek: "buổi/tuần",
    classSize: "Sĩ số",
    classSizeStudents: "học viên",
    courseLevel: "Trình độ",
    curriculum: "Chương trình học",
    whyThisCourse: "Tại sao chọn khóa học này",
    registerForCourse: "Đăng ký khóa học",
    regSuccessTitle: "Cảm ơn bạn!",
    regSuccessMsg: "Chúng tôi sẽ liên hệ bạn trong vòng 24 giờ để xác nhận đăng ký.",
    otherCourses: "Các khóa học khác",
    formName: "Họ và tên",
    formPhone: "Số điện thoại",
    formEmail: "Email",
    formChild: "Tên con",
    formAge: "Tuổi",
    submitReg: "Gửi đăng ký",
    submittingReg: "Đang gửi...",
    
    // Homepage additional translations
    limitedOffer: "Ưu đãi có hạn - Giảm 30%",
    freeConsult: "Tư vấn miễn phí",
    hotDeal: "ƯU ĐÃI HOT",
    freeTrialClass: "Học thử miễn phí",
    tryBeforeEnroll: "Trải nghiệm trước khi đăng ký",
    noPaymentRequired: "Không cần thanh toán",
    happyStudents: "Học viên hài lòng",
    yearsExperience: "Năm kinh nghiệm",
    studentsEnrolled: "Học viên đã đăng ký",
    expertTeachers: "Giáo viên chuyên môn",
    learningCenters: "Cơ sở học tập",
    learningPathTitle: "Chọn Lộ Trình Học Tập",
    learningPathSubtitle: "Chương trình học cá nhân hóa cho mọi độ tuổi",
    pathKids: "LERA Kids",
    pathKidsDesc: "Tiếng Anh vui nhộn và tương tác cho trẻ nhỏ",
    pathJunior: "LERA Junior",
    pathJuniorDesc: "Xây dựng nền tảng vững chắc với chương trình Cambridge",
    pathTeen: "LERA Teens",
    pathTeenDesc: "Tiếng Anh học thuật & luyện thi",
    agesLabel: "Độ tuổi",
    learnMore: "Xem thêm",
    whyChooseUs: "Tại Sao Chọn LERA Academy",
    modernMethod: "Phương pháp hiện đại",
    modernMethodDesc: "Kết hợp công nghệ AI với kỹ thuật giảng dạy đã được chứng minh",
    smallClass: "Lớp học nhỏ",
    smallClassDesc: "Tối đa 12 học viên mỗi lớp để được chú ý cá nhân",
    intlCertificate: "Chứng chỉ quốc tế",
    intlCertificateDesc: "Chuẩn bị cho học viên thi Cambridge, IELTS, TOEFL",
    meetTeachers: "Đội ngũ giáo viên",
    teachersSubtitle: "Giáo viên bản ngữ giàu kinh nghiệm từ các nước nói tiếng Anh",
    experience: "kinh nghiệm",
    parentsSay: "Phụ huynh nói gì",
    parentOf: "Phụ huynh của",
    viewCourses: "Xem khóa học",
    contactUs: "Liên hệ",
    
    // ===== DASHBOARD TRANSLATIONS =====
    // Dashboard Navigation
    dashboard: "Bảng điều khiển",
    welcomeBack: "Chào mừng trở lại! Đây là tình hình tại LERA Academy.",
    
    // Chairman Panel
    chairmanPanel: "Bảng Chủ Tịch",
    controlCenter: "Trung tâm điều khiển",
    userManagement: "Quản lý người dùng",
    staffManagement: "Nhân sự (Giáo viên/Phụ huynh/Admin)",
    boardOfDirectors: "Hội đồng quản trị",
    directors: "Giám đốc",
    orgStructure: "Cơ cấu tổ chức & Báo cáo",
    rolesPermissions: "Vai trò & Quyền hạn",
    departments: "Phòng ban",
    excelDataImport: "Nhập dữ liệu Excel",
    systemSettings: "Cài đặt hệ thống",
    dropdownOptions: "Tùy chọn danh sách",
    pendingApprovals: "Chờ phê duyệt",
    auditLogs: "Nhật ký kiểm tra",
    
    // Organization
    organization: "Tổ chức",
    allCenters: "Tất cả cơ sở",
    addNewCenter: "Thêm cơ sở mới",
    centerAnalytics: "Phân tích cơ sở",
    dataImport: "Nhập dữ liệu",
    
    // Public Website
    publicWebsite: "Website công khai",
    homePageEditor: "Chỉnh sửa trang chủ",
    heroSection: "Phần Hero",
    websiteSettings: "Cài đặt website",
    coursesSection: "Phần khóa học",
    aboutPage: "Trang giới thiệu",
    contactPage: "Trang liên hệ",
    centersPage: "Trang cơ sở",
    testimonials: "Đánh giá",
    blogPosts: "Blog & Bài viết",
    faqManagement: "Quản lý FAQ",
    branding: "Thương hiệu",
    footer: "Chân trang",
    seoSettings: "Cài đặt SEO",
    
    // Academy
    academy: "Học viện",
    studentsNav: "Học viên",
    teachersNav: "Giáo viên",
    coursesNav: "Khóa học",
    classes: "Lớp học",
    classrooms: "Phòng học",
    enrollments: "Đăng ký học",
    
    // Attendance & Leave
    attendanceLeave: "Điểm danh & Nghỉ phép",
    myAttendance: "Điểm danh của tôi",
    myLeaveRequests: "Đơn nghỉ phép của tôi",
    leaveApprovals: "Duyệt nghỉ phép",
    approvals: "Phê duyệt",
    overview: "Tổng quan",
    studentAttendance: "Điểm danh học viên",
    teacherAttendance: "Điểm danh giáo viên",
    userAttendance: "Điểm danh người dùng",
    
    // Exams & Progress
    examsProgress: "Thi cử & Tiến độ",
    mySchedule: "Lịch của tôi",
    myGrades: "Điểm của tôi",
    taGrades: "Điểm trợ giảng",
    exams: "Kỳ thi",
    results: "Kết quả",
    progressReports: "Báo cáo tiến độ",
    
    // Finance
    finance: "Tài chính",
    financeDashboard: "Bảng điều khiển tài chính",
    payments: "Thanh toán",
    invoices: "Hóa đơn",
    studentFeeManagement: "Quản lý học phí",
    feePlans: "Gói học phí",
    feeRules: "Quy tắc học phí",
    discounts: "Giảm giá",
    refunds: "Hoàn tiền",
    payroll: "Bảng lương",
    reports: "Báo cáo",
    
    // CRM
    crm: "CRM",
    leads: "Khách hàng tiềm năng",
    followUps: "Theo dõi",
    registrations: "Đăng ký",
    
    // Parent Communications
    parentCommunications: "Liên lạc phụ huynh",
    
    // LERA Connect
    leraConnect: "LERA Connect",
    
    // AI & Analytics
    aiAnalytics: "AI & Phân tích",
    aiGateway: "Cổng AI",
    gamification: "Trò chơi hóa",
    
    // Student Panel
    myClasses: "Lớp của tôi",
    assignments: "Bài tập",
    grades: "Điểm số",
    attendance: "Điểm danh",
    messages: "Tin nhắn",
    myProfile: "Hồ sơ của tôi",
    
    // Parent Panel
    children: "Con em",
    schedule: "Lịch học",
    communication: "Liên lạc",
    
    // TA Panel
    gradesAssessment: "Điểm số & Đánh giá",
    tasks: "Nhiệm vụ",
    
    // Dashboard Stats
    totalStudents: "Tổng học viên",
    totalTeachers: "Tổng giáo viên",
    totalCenters: "Tổng cơ sở",
    monthlyRevenue: "Doanh thu tháng",
    activeClasses: "Lớp đang học",
    attendanceRate: "Tỷ lệ điểm danh",
    superadminQuickActions: "Thao tác nhanh SuperAdmin",
    editHomepage: "Sửa trang chủ",
    editCourses: "Sửa khóa học",
    recentActivities: "Hoạt động gần đây",
    viewAll: "Xem tất cả",
    pendingLeads: "Khách hàng chờ",
    awaitingFollowup: "Đang chờ liên hệ",
    converted: "Đã chuyển đổi",
    newLeads: "Khách mới",
    centerPerformance: "Hiệu suất cơ sở",
    welcomeBackAdmin: "Chào mừng trở lại, Quản trị viên",
    viewWebsite: "Xem trang web",
    quickLinks: "Liên kết nhanh",
    manageCenters: "Quản lý tất cả cơ sở",
    manageHomepage: "Sửa trang chủ",
    manageCourses: "Quản lý khóa học",
    manageBlog: "Quản lý blog",
    manageTestimonials: "Quản lý đánh giá",
    brandSettings: "Cài đặt thương hiệu",
    centersManagement: "Quản lý cơ sở",
    
    // Common Actions
    add: "Thêm",
    edit: "Sửa",
    delete: "Xóa",
    save: "Lưu",
    cancel: "Hủy",
    search: "Tìm kiếm",
    filter: "Lọc",
    export: "Xuất",
    import: "Nhập",
    refresh: "Làm mới",
    loading: "Đang tải...",
    noData: "Không có dữ liệu",
    actions: "Thao tác",
    status: "Trạng thái",
    active: "Hoạt động",
    inactive: "Không hoạt động",
    pending: "Đang chờ",
    completed: "Hoàn thành",
    
    // Time
    today: "Hôm nay",
    week: "Tuần",
    month: "Tháng",
    year: "Năm",
    
    // Profile
    profile: "Hồ sơ",
    settings: "Cài đặt",
    logout: "Đăng xuất",
    notifications: "Thông báo",
    markAllRead: "Đánh dấu đã đọc",
    noNotifications: "Không có thông báo",
    viewAllNotifications: "Xem tất cả thông báo",
    
    // Errors & Messages
    error: "Lỗi",
    success: "Thành công",
    warning: "Cảnh báo",
    info: "Thông tin",
    confirmDelete: "Bạn có chắc chắn muốn xóa mục này?",
    deleteSuccess: "Xóa thành công",
    saveSuccess: "Lưu thành công",
    updateSuccess: "Cập nhật thành công",
    
    // Marketing
    socialMediaPosts: "Bài đăng mạng xã hội",
    marketingCampaigns: "Chiến dịch marketing",
    socialAnalytics: "Phân tích mạng xã hội",
    platforms: "Nền tảng",
    reach: "Tiếp cận",
    likes: "Thích",
    shares: "Chia sẻ",
    comments: "Bình luận",
    followers: "Người theo dõi",
    engagementRate: "Tỷ lệ tương tác",
    scheduled: "Đã lên lịch",
    published: "Đã đăng",
    draft: "Bản nháp",
    
    // Role-specific Dashboard Labels
    directorDashboard: "Bảng điều khiển Giám đốc",
    strategicOverview: "Tổng quan chiến lược hoạt động",
    totalStaff: "Tổng nhân sự",
    totalRevenue: "Tổng doanh thu",
    quickActions: "Thao tác nhanh",
    ceoDashboard: "Bảng điều khiển CEO",
    executiveOverview: "Tổng quan điều hành tổ chức",
    growthRate: "Tốc độ tăng trưởng",
    financialReports: "Báo cáo tài chính",
    strategicPlans: "Kế hoạch chiến lược",
    analytics: "Phân tích",
    staffDashboard: "Bảng điều khiển Nhân viên",
    welcomeStaff: "Chào mừng",
    tasksToday: "Nhiệm vụ hôm nay",
    taDashboard: "Bảng điều khiển Trợ giảng",
    welcomeTA: "Chào mừng",
    assignedClasses: "Lớp phụ trách",
    studentsHelping: "Học viên hỗ trợ",
    todaySessions: "Buổi học hôm nay",
    teacherDashboard: "Bảng điều khiển Giáo viên",
    welcomeTeacher: "Chào mừng trở lại",
    myStudents: "Học viên của tôi",
    pendingAttendance: "Chờ điểm danh",
    takeAttendance: "Điểm danh",
    studentList: "Danh sách học viên",
    todaysSchedule: "Lịch hôm nay",
    room: "Phòng",
    studentsDash: "học viên",
    inProgress: "Đang diễn ra",
    upcoming: "Sắp tới",
    studentDashboard: "Bảng điều khiển Học viên",
    welcomeStudent: "Chào mừng trở lại",
    myCourses: "Khóa học của tôi",
    upcomingClasses: "Lớp sắp tới",
    assignmentsDue: "Bài tập cần nộp",
    parentDashboard: "Bảng điều khiển Phụ huynh",
    monitorProgress: "Theo dõi tiến độ con em",
    childrenProgress: "Tiến độ con em",
    avgAttendance: "TB điểm danh",
    upcomingFees: "Học phí sắp đến hạn",
    centerAdminDashboard: "Bảng điều khiển Quản trị cơ sở",
    manageCenter: "Quản lý hoạt động cơ sở",
    centerManagerDashboard: "Bảng điều khiển Quản lý cơ sở",
    academicManagerDashboard: "Bảng điều khiển Quản lý học vụ",
    myTasks: "Nhiệm vụ của tôi",
    myCalendar: "Lịch của tôi",
    
    // Recent Activity
    recentActivity: "Hoạt động gần đây",
    noRecentActivity: "Không có hoạt động gần đây",
    systemReady: "Hệ thống sẵn sàng",
    paymentReceived: "Thanh toán đã nhận",
    newStudent: "Học viên mới đăng ký",
    newTeacher: "Giáo viên mới thêm",
    courseUpdated: "Khóa học đã cập nhật",
    newStudentRegistered: "Học viên mới đăng ký",
    newUserRegistered: "Người dùng mới đăng ký",
    newEnrollment: "Đăng ký mới",
    recentStudents: "Học viên gần đây",
    noStudentsFound: "Không tìm thấy học viên",
    searchStudents: "Tìm kiếm học viên...",
    viewStudents: "Xem học viên",
    created: "Đã tạo",
    recentPayments: "Thanh toán gần đây",
    
    // Login Page
    backToHome: "Quay về trang chủ",
    welcomeBackLogin: "Chào mừng trở lại",
    signInToAccount: "Đăng nhập vào tài khoản LERA Academy",
    emailAddress: "Địa chỉ Email",
    emailPlaceholder: "ban@example.com",
    password: "Mật khẩu",
    rememberMe: "Ghi nhớ đăng nhập",
    forgotPassword: "Quên mật khẩu?",
    signIn: "Đăng nhập",
    signingIn: "Đang đăng nhập...",
    noAccount: "Chưa có tài khoản?",
    contactAdmin: "Liên hệ Admin",

    // Finance Module (extended)
    financeOverview: "Tổng quan tài chính toàn diện",
    totalRevenueLabel: "Tổng doanh thu",
    outstandingBalance: "Số dư chưa thanh toán",
    refundedAmount: "Đã hoàn tiền",
    collectionRate: "Tỉ lệ thu",
    studentsPaying: "Học viên đang đóng",
    overdueCount: "Quá hạn",
    invoiceCountLabel: "Hóa đơn",
    generateManage: "Tạo & quản lý",
    trackPayments: "Theo dõi thanh toán",
    configureFees: "Cấu hình học phí",
    processRefunds: "Xử lý hoàn tiền",
    manageDiscounts: "Quản lý giảm giá",
    studentPlans: "Gói học viên",
    paymentPlans: "Kế hoạch thanh toán",
    revenueByCenter: "Doanh thu theo cơ sở",
    recentTransactions: "Giao dịch gần đây",
    monthlyTrend: "Xu hướng hàng tháng",
    noTransactions: "Không có giao dịch gần đây",

    // Academy Module (extended)
    academyDashboard: "Bảng điều khiển Học viện",
    academyOverview: "Quản lý và tổng quan học thuật",
    totalStudentsLabel: "Tổng học viên",
    totalTeachersLabel: "Tổng giáo viên",
    totalClassesLabel: "Tổng lớp học",
    totalCoursesLabel: "Tổng khóa học",
    activeEnrollments: "Đăng ký đang hoạt động",
    parents: "Phụ huynh",
    staffMembers: "Nhân viên",
    manageStudents: "Quản lý học viên",
    manageTeachers: "Quản lý giáo viên",
    manageClasses: "Quản lý lớp học",
    addNew: "Thêm mới",
    confirm: "Xác nhận",
    close: "Đóng",
    all: "Tất cả",

    // Exams Module
    examsDashboard: "Kỳ thi & Đánh giá",
    examOverview: "Quản lý kỳ thi và đánh giá học viên",
    upcomingExams: "Kỳ thi sắp tới",
    examResults: "Kết quả thi",
    examProgress: "Theo dõi tiến độ",
    averageScore: "Điểm trung bình",
    passRate: "Tỉ lệ đạt",
    totalExams: "Tổng kỳ thi",
    createExam: "Tạo kỳ thi",

    // Attendance Module (extended)
    attendanceDashboard: "Quản lý điểm danh",
    attendanceOverview: "Theo dõi và quản lý điểm danh",
    presentToday: "Có mặt hôm nay",
    absentToday: "Vắng hôm nay",
    lateToday: "Trễ hôm nay",
    attendanceRateLabel: "Tỉ lệ chuyên cần",
    markAttendance: "Điểm danh",
    viewAttendance: "Xem điểm danh",
    attendanceHistory: "Lịch sử điểm danh",

    // CRM Module (extended)
    crmDashboard: "Bảng điều khiển CRM",
    crmOverview: "Quản lý khách hàng tiềm năng",
    totalLeads: "Tổng khách tiềm năng",
    conversionRate: "Tỉ lệ chuyển đổi",
    leadsPipeline: "Pipeline khách hàng",
    communications: "Liên lạc",
    automations: "Tự động hóa",
    tags: "Nhãn",

    // Reports Module
    reportsDashboard: "Báo cáo & Phân tích",
    generateReport: "Tạo báo cáo",
    downloadReport: "Tải báo cáo",
    revenueReport: "Báo cáo doanh thu",
    performanceReport: "Báo cáo hiệu suất",
    attendanceReport: "Báo cáo chuyên cần",
    enrollmentReport: "Báo cáo tuyển sinh",

    // Common Dashboard Labels
    manage: "Quản lý",
    configuration: "Cấu hình",
    thisWeek: "Tuần này",
    thisMonth: "Tháng này",
    lastMonth: "Tháng trước",
    dateRange: "Khoảng thời gian",
    from: "Từ",
    to: "Đến",
    apply: "Áp dụng",
    reset: "Đặt lại",
    details: "Chi tiết",
    view: "Xem",
    back: "Quay lại",
    next: "Tiếp",
    previous: "Trước",
    showing: "Đang hiển thị",
    of: "của",
    perPage: "mỗi trang",
    noResults: "Không tìm thấy kết quả",
    searchPlaceholder: "Tìm kiếm...",
    sortBy: "Sắp xếp theo",
    ascending: "Tăng dần",
    descending: "Giảm dần",
    createdAt: "Ngày tạo",
    updatedAt: "Ngày cập nhật",
    description: "Mô tả",
    type: "Loại",
    category: "Danh mục",
    amount: "Số tiền",
    date: "Ngày",
    time: "Giờ",
    notes: "Ghi chú",
    attachments: "Đính kèm",
    priority: "Ưu tiên",
    high: "Cao",
    medium: "Trung bình",
    low: "Thấp",
    approved: "Đã duyệt",
    rejected: "Từ chối",
    inReview: "Đang xem xét",
    submitted: "Đã nộp",
    quarter: "Quý",

    // Chairman Dashboard
    chairmanControlPanel: "Bảng Điều Khiển Chủ Tịch",
    fullAdminAccess: "Quyền quản trị đầy đủ cho tất cả thành phần hệ thống",
    systemOverview: "Tổng Quan Hệ Thống",
    usersAndRoles: "Người Dùng & Vai Trò",
    pendingApprovalsTab: "Chờ Duyệt",
    centersTab: "Cơ Sở",
    departmentsTab: "Phòng Ban",
    coursesAndPrograms: "Khóa Học & Chương Trình",
    marketingTab: "Marketing",
    websiteContent: "Nội Dung Website",
    totalUsers: "Tổng Người Dùng",
    pendingApprovalsCount: "Chờ Duyệt",
    addUser: "Thêm Người Dùng",
    addCenter: "Thêm Cơ Sở",
    reviewApprovals: "Xem Duyệt",
    systemRoles: "Vai Trò Hệ Thống",
    usersRolesManagement: "Quản Lý Người Dùng & Vai Trò",
    addNewUser: "+ Thêm Người Dùng Mới",
    searchUsers: "Tìm kiếm người dùng...",
    allCaughtUp: "Đã xử lý hết!",
    noPendingApprovals: "Không có yêu cầu chờ duyệt.",
    submittedBy: "Gửi bởi",
    approve: "Duyệt",
    reject: "Từ chối",
    noAddress: "Chưa có địa chỉ",
    noPhone: "Chưa có SĐT",
    departmentsManagement: "Quản Lý Phòng Ban",
    addDepartment: "+ Thêm Phòng Ban",
    department: "Phòng Ban",
    code: "Mã",
    addCourse: "+ Thêm Khóa Học",
    noDescription: "Chưa có mô tả",
    allLevels: "Tất Cả Cấp Độ",
    general: "Chung",
    addSetting: "+ Thêm Cài Đặt",
    key: "Khóa",
    value: "Giá Trị",
    public: "Công Khai",
    yes: "Có",
    no: "Không",
    saveChanges: "Lưu Thay Đổi",
    user: "Người Dùng",
    websiteContentManagement: "Quản Lý Nội Dung Website",
    managePublicContent: "Quản lý tất cả nội dung website công khai",
    openContentManager: "Mở Trình Quản Lý Nội Dung →",
    homePage: "Trang Chủ",
    privacyPolicy: "Chính Sách Bảo Mật",
    termsOfService: "Điều Khoản Dịch Vụ",
    updatedSuccessfully: "Cập nhật thành công!",
    failedToUpdate: "Cập nhật thất bại. Vui lòng thử lại.",
    errorSaving: "Lỗi khi lưu thay đổi.",
    deletedSuccessfully: "Xóa thành công!",
    failedToDelete: "Xóa thất bại.",

    // Reports
    viewDownloadReports: "Xem và tải xuống các báo cáo của bạn",
    totalReports: "Tổng Báo Cáo",
    ready: "Sẵn Sàng",
    generating: "Đang Tạo",
    reportTypes: "Loại Báo Cáo",
    academic: "Học Tập",
    financial: "Tài Chính",
    performance: "Hiệu Suất",
    download: "Tải Xuống",
    failed: "Thất Bại",
    generateNewReport: "Tạo Báo Cáo Mới",
    reportType: "Loại Báo Cáo",
    academicReport: "Báo Cáo Học Tập",
    financialReport: "Báo Cáo Tài Chính",
    format: "Định Dạng",
    generate: "Tạo",
    noReportsFound: "Không tìm thấy báo cáo",
    failedToDownload: "Không thể tải xuống báo cáo",

    // Connect / Messaging
    messaging: "Nhắn Tin",
    conversations: "Cuộc Hội Thoại",
    newMessage: "Tin Nhắn Mới",
    typeMessage: "Nhập tin nhắn...",
    send: "Gửi",
    online: "Trực Tuyến",
    offline: "Ngoại Tuyến",
    noConversations: "Chưa có cuộc hội thoại nào",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("VI");
  const [mounted, setMounted] = useState(false);

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem("lera-language") as Language;
    if (savedLanguage && (savedLanguage === "EN" || savedLanguage === "VI")) {
      setLanguageState(savedLanguage);
    }
    setMounted(true);
  }, []);

  // Save language to localStorage when changed
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("lera-language", lang);
  };

  // Translation helper function
  const t = (key: string): string => {
    const trans = translations[language] as Record<string, string>;
    return trans[key] || key;
  };

  // Prevent hydration mismatch by not rendering until mounted
  if (!mounted) {
    return (
      <LanguageContext.Provider value={{ language: "VI", setLanguage, t }}>
        {children}
      </LanguageContext.Provider>
    );
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
