import type { Metadata, Viewport } from 'next'
import './globals.css'
import { LanguageProvider } from './context/LanguageContext'
import { WebsiteSettingsProvider } from '@/hooks/useWebsiteSettings'
import { ErrorBoundary } from '@/components/ErrorBoundary'
import { ToastContainer } from '@/components/Toast'
import FloatingContact from './components/FloatingContact'

export const metadata: Metadata = {
  title: {
    default: 'LERA Academy - Where Excellence is the Standard | Trung tâm Anh ngữ hàng đầu Hải Phòng',
    template: '%s | LERA Academy'
  },
  description: 'LERA Academy - Trung tâm Anh ngữ cao cấp với giáo viên bản ngữ tại Vinhomes Marina, Hải Phòng. Chương trình Cambridge cho mọi lứa tuổi từ 2.5 tuổi. ☎️ 0387.633.141',
  keywords: ['LERA Academy', 'học tiếng Anh', 'Hải Phòng', 'Vinhomes Marina', 'giáo viên bản ngữ', 'Cambridge English', 'tiếng Anh trẻ em', 'IELTS', 'SAT'],
  authors: [{ name: 'LERA Academy' }],
  creator: 'LERA Academy',
  publisher: 'LERA Academy',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://lera.edu.vn'),
  alternates: {
    canonical: '/',
    languages: {
      'en-US': '/en',
      'vi-VN': '/vi',
    },
  },
  openGraph: {
    title: 'LERA Academy - Where Excellence is the Standard',
    description: 'Trung tâm Anh ngữ cao cấp với giáo viên bản ngữ. Chương trình Cambridge cho mọi lứa tuổi.',
    url: 'https://lera.edu.vn',
    siteName: 'LERA Academy',
    images: [
      {
        url: '/images/gallery/lera-hero.jpg',
        width: 1200,
        height: 630,
        alt: 'LERA Academy - Where Excellence is the Standard',
      },
    ],
    locale: 'vi_VN',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'LERA Academy - Where Excellence is the Standard',
    description: 'Trung tâm Anh ngữ cao cấp với giáo viên bản ngữ tại Hải Phòng',
    images: ['/images/gallery/lera-hero.jpg'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  // Add a real token from Google Search Console here when verifying:
  // verification: { google: 'xxxxxxxxxxxxxxxx' },
  // PWA manifest + apple-touch-icon. Generated by
  // `npm run mobile:icons` from public/icons/logo.svg; the manifest is
  // referenced here so the browser knows the app is installable.
  manifest: '/manifest.webmanifest',
  icons: {
    icon: [
      { url: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: '/icons/icon-192.png',
  },
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  themeColor: '#1e40af',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const orgJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'EducationalOrganization',
    name: 'LERA Academy',
    alternateName: 'Trung tâm Anh ngữ LERA',
    description: 'Premium English language centre in Hải Phòng, Vietnam — Cambridge-aligned programmes, native and qualified teachers, small classes.',
    url: 'https://lera.edu.vn',
    logo: 'https://lera.edu.vn/images/logo/lera-logo.png',
    image: 'https://lera.edu.vn/images/gallery/lera-hero.jpg',
    telephone: '+84387633141',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'Vinhomes Marina',
      addressLocality: 'Hải Phòng',
      addressCountry: 'VN',
    },
    sameAs: ['https://www.facebook.com/profile.php?id=61580971978601'],
    areaServed: 'Hải Phòng, Vietnam',
  }

  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(orgJsonLd) }}
        />
      </head>
      <body className="min-w-0 overflow-x-hidden">
        <ErrorBoundary>
          <WebsiteSettingsProvider>
            <LanguageProvider>
              {children}
            </LanguageProvider>
          </WebsiteSettingsProvider>
          <FloatingContact />
          <ToastContainer />
        </ErrorBoundary>
      </body>
    </html>
  )
}
