import type { Metadata, Viewport } from 'next'
import { Be_Vietnam_Pro, Inter } from 'next/font/google'
import './globals.css'

// Premium type system (Modern & clean). Both ship full Vietnamese diacritics.
const display = Be_Vietnam_Pro({
  subsets: ['latin', 'latin-ext', 'vietnamese'],
  weight: ['600', '700', '800'],
  variable: '--font-display',
  display: 'swap',
})
const sans = Inter({
  subsets: ['latin', 'latin-ext', 'vietnamese'],
  weight: ['400', '500', '600'],
  variable: '--font-sans',
  display: 'swap',
})
import { LanguageProvider } from './context/LanguageContext'
import { WebsiteSettingsProvider } from '@/hooks/useWebsiteSettings'
import { ErrorBoundary } from '@/components/ErrorBoundary'
import { ToastContainer } from '@/components/Toast'
import FloatingCTA from './components/FloatingCTA'
import BrandTheme from './components/BrandTheme'
import CursorFollower from './components/CursorFollower'

// Static SEO defaults (always valid). `generateMetadata` below overlays the
// Chairman's saved seo_settings on top of these when present, falling back to
// these defaults on any error — so the SEO editor is live without losing a
// reliable baseline. (Endpoint is the public GET /api/cms-settings/value/*.)
const SEO_SETTINGS_URL =
  (process.env.ACADEMY_SERVICE_URL || 'http://localhost:8082') + '/api/cms-settings/value/seo_settings'

const baseMetadata: Metadata = {
  title: {
    default: 'LERA Academy - Where Excellence is the Standard | Trung tâm Anh ngữ hàng đầu Hải Phòng',
    template: '%s | LERA Academy'
  },
  description: 'LERA Academy - Trung tâm Anh ngữ cao cấp với giáo viên bản ngữ tại Vinhomes Marina, Hải Phòng. Chương trình Cambridge cho mọi lứa tuổi từ 2.5 tuổi. ☎️ 0387.633.141',
  keywords: ['LERA Academy', 'học tiếng Anh', 'Hải Phòng', 'Vinhomes Marina', 'giáo viên bản ngữ', 'Cambridge English', 'tiếng Anh trẻ em', 'IELTS', 'SAT'],
  authors: [{ name: 'LERA Academy' }],
  creator: 'LERA Academy',
  publisher: 'LERA Academy',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://lera.edu.vn'),
  alternates: {
    canonical: '/',
    languages: {
      'en-US': '/en',
      'vi-VN': '/vi',
    },
  },
  openGraph: {
    title: 'LERA Academy - Where Excellence is the Standard',
    description: 'Trung tâm Anh ngữ cao cấp với giáo viên bản ngữ. Chương trình Cambridge cho mọi lứa tuổi.',
    url: 'https://lera.edu.vn',
    siteName: 'LERA Academy',
    images: [
      {
        url: '/images/gallery/lera-hero.jpg',
        width: 1200,
        height: 630,
        alt: 'LERA Academy - Where Excellence is the Standard',
      },
    ],
    locale: 'vi_VN',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'LERA Academy - Where Excellence is the Standard',
    description: 'Trung tâm Anh ngữ cao cấp với giáo viên bản ngữ tại Hải Phòng',
    images: ['/images/gallery/lera-hero.jpg'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  // Add a real token from Google Search Console here when verifying:
  // verification: { google: 'xxxxxxxxxxxxxxxx' },
  // PWA manifest + apple-touch-icon. Generated by
  // `npm run mobile:icons` from public/icons/logo.svg; the manifest is
  // referenced here so the browser knows the app is installable.
  manifest: '/manifest.webmanifest',
  icons: {
    icon: [
      { url: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: '/icons/icon-192.png',
  },
}

export async function generateMetadata(): Promise<Metadata> {
  try {
    const res = await fetch(SEO_SETTINGS_URL, { next: { revalidate: 300 } })
    if (!res.ok) return baseMetadata
    const raw = await res.text()
    if (!raw) return baseMetadata
    const s: any = JSON.parse(raw)
    // Site primary locale is vi_VN; prefer VI, then EN, then keep the static default.
    const pick = (b: any): string | undefined => (b && (b.vi || b.en)) || undefined
    const title = pick(s?.title)
    const description = pick(s?.description)
    const kw = pick(s?.keywords)
    const ogImage = typeof s?.ogImage === 'string' && s.ogImage ? s.ogImage : undefined
    if (!title && !description && !kw && !ogImage) return baseMetadata
    return {
      ...baseMetadata,
      ...(title ? { title: { default: title, template: '%s | LERA Academy' } } : {}),
      ...(description ? { description } : {}),
      ...(kw ? { keywords: kw.split(',').map((k: string) => k.trim()).filter(Boolean) } : {}),
      openGraph: {
        ...baseMetadata.openGraph,
        ...(title ? { title } : {}),
        ...(description ? { description } : {}),
        ...(ogImage ? { images: [{ url: ogImage, width: 1200, height: 630, alt: title || 'LERA Academy' }] } : {}),
      },
      twitter: {
        ...baseMetadata.twitter,
        ...(title ? { title } : {}),
        ...(description ? { description } : {}),
        ...(ogImage ? { images: [ogImage] } : {}),
      },
    }
  } catch {
    return baseMetadata
  }
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  themeColor: '#1e40af',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const orgJsonLd = {
    '@context': 'https://schema.org',
    '@type': ['EducationalOrganization', 'LocalBusiness'],
    '@id': 'https://lera.edu.vn/#organization',
    name: 'LERA Academy',
    alternateName: 'Trung tâm Anh ngữ LERA',
    description: 'Premium English language centre in Hải Phòng, Vietnam — Cambridge-aligned programmes, native and qualified teachers, small classes.',
    url: 'https://lera.edu.vn',
    logo: 'https://lera.edu.vn/images/logo/lera-logo.png',
    image: 'https://lera.edu.vn/images/gallery/lera-hero.jpg',
    telephone: '+84387633141',
    priceRange: '$$',
    address: {
      '@type': 'PostalAddress',
      streetAddress: '95 Hải Đăng, Khu đô thị Vinhomes Marina, Phường An Biên',
      addressLocality: 'Hải Phòng',
      addressRegion: 'Hải Phòng',
      addressCountry: 'VN',
    },
    // TODO: replace with the EXACT pin from your Google Business Profile
    // (Google Maps → your listing → share → the lat,lng in the URL). These are approximate.
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 20.8449,
      longitude: 106.6881,
    },
    openingHoursSpecification: [
      {
        '@type': 'OpeningHoursSpecification',
        dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        opens: '08:00',
        closes: '21:00',
      },
    ],
    sameAs: [
      'https://www.facebook.com/profile.php?id=61580971978601',
      'https://instagram.com/leraacademy',
      'https://youtube.com/@leraacademy',
      'https://tiktok.com/@leraacademy',
    ],
    areaServed: { '@type': 'City', name: 'Hải Phòng' },
  }

  return (
    <html lang="en" className={`${display.variable} ${sans.variable}`}>
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(orgJsonLd) }}
        />
      </head>
      <body className="min-w-0 overflow-x-hidden">
        <BrandTheme />
        <CursorFollower />
        <ErrorBoundary>
          <WebsiteSettingsProvider>
            <LanguageProvider>
              {children}
              {/* Single global quick-contact / promo widget (public pages only; hides on dashboard) */}
              <FloatingCTA />
            </LanguageProvider>
          </WebsiteSettingsProvider>
          <ToastContainer />
        </ErrorBoundary>
      </body>
    </html>
  )
}
