import type { Metadata, Viewport } from 'next'
import './globals.css'
import { LanguageProvider } from './context/LanguageContext'
import { WebsiteSettingsProvider } from '@/hooks/useWebsiteSettings'
import { ErrorBoundary } from '@/components/ErrorBoundary'
import { ToastContainer } from '@/components/Toast'

export const metadata: Metadata = {
  title: {
    default: 'LERA Academy - Where Excellence is the Standard | Trung tâm Anh ngữ hàng đầu Hải Phòng',
    template: '%s | LERA Academy'
  },
  description: 'LERA Academy - Trung tâm Anh ngữ cao cấp với giáo viên bản ngữ tại Vinhomes Marina, Hải Phòng. Chương trình Cambridge cho mọi lứa tuổi từ 2.5 tuổi. ☎️ 0387.633.141',
  keywords: ['LERA Academy', 'học tiếng Anh', 'Hải Phòng', 'Vinhomes Marina', 'giáo viên bản ngữ', 'Cambridge English', 'tiếng Anh trẻ em', 'IELTS', 'SAT'],
  authors: [{ name: 'LERA Academy' }],
  creator: 'LERA Academy',
  publisher: 'LERA Academy',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://lera.edu.vn'),
  alternates: {
    canonical: '/',
    languages: {
      'en-US': '/en',
      'vi-VN': '/vi',
    },
  },
  openGraph: {
    title: 'LERA Academy - Where Excellence is the Standard',
    description: 'Trung tâm Anh ngữ cao cấp với giáo viên bản ngữ. Chương trình Cambridge cho mọi lứa tuổi.',
    url: 'https://lera.edu.vn',
    siteName: 'LERA Academy',
    images: [
      {
        url: '/images/gallery/lera-hero.jpg',
        width: 1200,
        height: 630,
        alt: 'LERA Academy - Where Excellence is the Standard',
      },
    ],
    locale: 'vi_VN',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'LERA Academy - Where Excellence is the Standard',
    description: 'Trung tâm Anh ngữ cao cấp với giáo viên bản ngữ tại Hải Phòng',
    images: ['/images/gallery/lera-hero.jpg'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'google-site-verification-code',
  },
  // PWA manifest + apple-touch-icon. Generated by
  // `npm run mobile:icons` from public/icons/logo.svg; the manifest is
  // referenced here so the browser knows the app is installable.
  manifest: '/manifest.webmanifest',
  icons: {
    icon: [
      { url: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: '/icons/icon-192.png',
  },
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  themeColor: '#1e40af',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body className="min-w-0 overflow-x-hidden">
        <ErrorBoundary>
          <WebsiteSettingsProvider>
            <LanguageProvider>
              {children}
            </LanguageProvider>
          </WebsiteSettingsProvider>
          <ToastContainer />
        </ErrorBoundary>
      </body>
    </html>
  )
}
