"use client";

import AdminCrudPage from "@/components/AdminCrudPage";

export default function AiLearningPathsAdminPage() {
  return (
    <AdminCrudPage
      title="🧭 AI Learning Paths"
      description="Personalised study trajectories generated by the AI gateway. Each path is a sequence of lessons / assessments tuned to a student level."
      endpoint="/api/ai/learning-paths"
      columns={[
        { key: "title", label: "Title", required: true },
        { key: "description", label: "Description", type: "textarea", hideInList: true },
        { key: "studentId", label: "Student", placeholder: "uuid" },
        { key: "level", label: "Level", placeholder: "BEGINNER / B1 / B2" },
        { key: "subject", label: "Subject" },
        { key: "status", label: "Status", type: "select", options: [
          { value: "DRAFT", label: "DRAFT" },
          { value: "ACTIVE", label: "ACTIVE" },
          { value: "COMPLETED", label: "COMPLETED" },
          { value: "ARCHIVED", label: "ARCHIVED" },
        ]},
        { key: "steps", label: "Steps (JSON)", type: "json", hideInList: true },
      ]}
      defaults={{ status: "DRAFT" }}
    />
  );
}
