server:
  port: 8088

spring:
  application:
    name: rule_engine

  datasource:
    url: jdbc:postgresql://localhost:5432/lera
    username: lera
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
