"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { apiFetch, apiUrl } from "../../../../lib/api";
import { useLanguage } from "../../../context/LanguageContext";
import Cookies from "js-cookie";

type Question = { q: string; options: string[]; correct: number; explain?: string };
type Game = { title: string; instructions?: string; questions: Question[]; usingRealAI?: boolean; tokensUsed?: number };
type Slide = { title: string; bullets: string[]; note?: string };
type Deck = { title: string; slides: Slide[]; usingRealAI?: boolean; tokensUsed?: number };

export default function TeacherAiStudioPage() {
  const { language } = useLanguage();
  const vi = language === "VI";
  const [plans, setPlans] = useState<any[]>([]);
  const [topic, setTopic] = useState("");
  const [level, setLevel] = useState("beginner");
  const [busy, setBusy] = useState<"" | "game" | "deck">("");
  const [game, setGame] = useState<Game | null>(null);
  const [deck, setDeck] = useState<Deck | null>(null);

  useEffect(() => {
    // best-effort: pull this teacher's lesson plans so they can generate from a real plan
    (async () => {
      try {
        const me = (await apiFetch("/api/teachers/me", {}, { silent: true }).catch(() => null)) as any;
        const tid = me?.id;
        if (tid) {
          const lp = (await apiFetch(`/api/lesson-plans/teacher/${tid}`, {}, { silent: true }).catch(() => [])) as any[];
          if (Array.isArray(lp)) setPlans(lp);
        }
      } catch {}
    })();
  }, []);

  const effectiveTopic = topic.trim() || (vi ? "Bài học tiếng Anh" : "English lesson");

  const generate = async (kind: "game" | "deck") => {
    setBusy(kind);
    if (kind === "game") setGame(null); else setDeck(null);
    try {
      const url = kind === "game" ? "/api/ai/generate-game" : "/api/ai/generate-presentation";
      const res = await apiFetch(url, { method: "POST", body: JSON.stringify({ topic: effectiveTopic, level }) });
      if (kind === "game") setGame(res as Game); else setDeck(res as Deck);
    } catch (e) {
      // graceful — endpoint returns a sample even without a key, so this is rare
    } finally {
      setBusy("");
    }
  };

  return (
    <div className="p-6 max-w-5xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">🎨 {vi ? "Xưởng AI cho Giáo viên" : "Teacher AI Studio"}</h1>
        <p className="text-sm text-gray-500">{vi ? "Biến giáo án thành trò chơi hoặc bài trình bày tương tác — do AI tạo." : "Turn a lesson plan into an interactive game or presentation — generated by AI."}</p>
      </div>

      {/* Input */}
      <div className="bg-white rounded-2xl border border-gray-100 shadow-card p-6">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {plans.length > 0 && (
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">{vi ? "Giáo án" : "Lesson plan"}</label>
              <select onChange={(e) => setTopic(e.target.value)} className="w-full px-3 py-2 border rounded-lg">
                <option value="">{vi ? "— Chọn giáo án —" : "— Pick a lesson plan —"}</option>
                {plans.map((p) => (
                  <option key={p.id} value={(p.title || p.topic || p.objective || "").toString()}>{p.title || p.topic || p.objective || "Lesson"}</option>
                ))}
              </select>
            </div>
          )}
          <div className={plans.length > 0 ? "" : "md:col-span-2"}>
            <label className="block text-sm font-medium text-gray-700 mb-1">{vi ? "Chủ đề bài học" : "Lesson topic"}</label>
            <input value={topic} onChange={(e) => setTopic(e.target.value)} placeholder={vi ? "VD: Thì hiện tại đơn cho trẻ 7–8 tuổi" : "e.g. Present simple tense for ages 7–8"} className="w-full px-3 py-2 border rounded-lg" />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">{vi ? "Trình độ" : "Level"}</label>
            <select value={level} onChange={(e) => setLevel(e.target.value)} className="w-full px-3 py-2 border rounded-lg">
              <option value="beginner">{vi ? "Mới bắt đầu" : "Beginner"}</option>
              <option value="intermediate">{vi ? "Trung cấp" : "Intermediate"}</option>
              <option value="advanced">{vi ? "Nâng cao" : "Advanced"}</option>
            </select>
          </div>
        </div>
        <div className="flex flex-wrap gap-3 mt-5">
          <button onClick={() => generate("game")} disabled={!!busy} className="px-5 py-2.5 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50">
            {busy === "game" ? (vi ? "Đang tạo…" : "Generating…") : `🎮 ${vi ? "Tạo trò chơi" : "Generate Game"}`}
          </button>
          <button onClick={() => generate("deck")} disabled={!!busy} className="px-5 py-2.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50">
            {busy === "deck" ? (vi ? "Đang tạo…" : "Generating…") : `🖥️ ${vi ? "Tạo bài trình bày" : "Generate Presentation"}`}
          </button>
        </div>
      </div>

      {game && <GamePlayer game={game} vi={vi} />}
      {deck && <Slideshow deck={deck} vi={vi} />}
    </div>
  );
}

function AiBadge({ live, tokens, vi }: { live?: boolean; tokens?: number; vi: boolean }) {
  return (
    <span className={`px-2 py-0.5 rounded-full text-xs ${live ? "bg-green-100 text-green-700" : "bg-gray-200 text-gray-600"}`}>
      {live ? `Claude · ${tokens || 0} tokens` : (vi ? "Mẫu (thêm khoá API trong AI Gateway)" : "Sample (add API key in AI Gateway)")}
    </span>
  );
}

function GamePlayer({ game, vi }: { game: Game; vi: boolean }) {
  const [i, setI] = useState(0);
  const [picked, setPicked] = useState<number | null>(null);
  const [score, setScore] = useState(0);
  const [done, setDone] = useState(false);
  const q = game.questions[i];
  const pick = (idx: number) => {
    if (picked !== null) return;
    setPicked(idx);
    if (idx === q.correct) setScore((s) => s + 1);
  };
  const next = () => {
    if (i + 1 >= game.questions.length) { setDone(true); return; }
    setI(i + 1); setPicked(null);
  };
  const restart = () => { setI(0); setPicked(null); setScore(0); setDone(false); };

  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-card p-6">
      <div className="flex items-center justify-between mb-1">
        <h2 className="text-lg font-bold">🎮 {game.title}</h2>
        <AiBadge live={game.usingRealAI} tokens={game.tokensUsed} vi={vi} />
      </div>
      {game.instructions && <p className="text-sm text-gray-500 mb-4">{game.instructions}</p>}
      {done ? (
        <div className="text-center py-10">
          <div className="text-5xl mb-3">🏆</div>
          <p className="text-2xl font-bold text-purple-700">{score} / {game.questions.length}</p>
          <p className="text-gray-500 mb-4">{vi ? "Hoàn thành!" : "Completed!"}</p>
          <button onClick={restart} className="px-5 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700">{vi ? "Chơi lại" : "Play again"}</button>
        </div>
      ) : (
        <div>
          <div className="flex justify-between text-xs text-gray-400 mb-2"><span>{vi ? "Câu" : "Question"} {i + 1}/{game.questions.length}</span><span>{vi ? "Điểm" : "Score"}: {score}</span></div>
          <p className="text-lg font-medium mb-4">{q.q}</p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {q.options.map((opt, idx) => {
              const isCorrect = idx === q.correct;
              const state = picked === null ? "" : isCorrect ? "bg-green-100 border-green-400 text-green-800" : picked === idx ? "bg-red-100 border-red-400 text-red-800" : "opacity-60";
              return (
                <button key={idx} onClick={() => pick(idx)} disabled={picked !== null}
                  className={`text-left px-4 py-3 rounded-lg border transition-all ${state || "border-gray-200 hover:border-purple-400 hover:bg-purple-50"}`}>
                  <span className="font-semibold mr-2">{String.fromCharCode(65 + idx)}.</span>{opt}
                </button>
              );
            })}
          </div>
          {picked !== null && (
            <div className="mt-4 flex items-center justify-between">
              <p className="text-sm text-gray-600">{q.explain}</p>
              <button onClick={next} className="px-5 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 whitespace-nowrap">{i + 1 >= game.questions.length ? (vi ? "Xem kết quả" : "See result") : (vi ? "Tiếp" : "Next")} →</button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function Slideshow({ deck, vi }: { deck: Deck; vi: boolean }) {
  const [i, setI] = useState(0);
  const s = deck.slides[i];
  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-card p-6">
      <div className="flex items-center justify-between mb-3">
        <h2 className="text-lg font-bold">🖥️ {deck.title}</h2>
        <AiBadge live={deck.usingRealAI} tokens={deck.tokensUsed} vi={vi} />
      </div>
      <div className="aspect-video bg-gradient-to-br from-brand-navy to-brand-navy600 text-white rounded-xl p-8 flex flex-col">
        <h3 className="text-2xl font-bold mb-5">{s.title}</h3>
        <ul className="space-y-3 flex-1">
          {(s.bullets || []).map((b, k) => (
            <li key={k} className="flex gap-3 text-lg"><span className="text-orange-300">•</span>{b}</li>
          ))}
        </ul>
        {s.note && <p className="text-white/60 text-sm mt-4 italic">📝 {s.note}</p>}
      </div>
      <div className="flex items-center justify-between mt-4">
        <button onClick={() => setI(Math.max(0, i - 1))} disabled={i === 0} className="px-4 py-2 bg-gray-100 rounded-lg disabled:opacity-40">← {vi ? "Trước" : "Prev"}</button>
        <span className="text-sm text-gray-500">{vi ? "Slide" : "Slide"} {i + 1} / {deck.slides.length}</span>
        <button onClick={() => setI(Math.min(deck.slides.length - 1, i + 1))} disabled={i + 1 >= deck.slides.length} className="px-4 py-2 bg-gray-100 rounded-lg disabled:opacity-40">{vi ? "Sau" : "Next"} →</button>
      </div>
    </div>
  );
}
