#!/usr/bin/env bash
# One-command production launch for the LERA stack on any Docker host.
#
#   ./scripts/launch-prod.sh              # HTTP on :80 (put behind Cloudflare for HTTPS)
#   DOMAIN=app.example.com ./scripts/launch-prod.sh --https   # direct HTTPS via Caddy + Let's Encrypt
#
# First run generates a .env with strong random secrets (gitignored — never committed),
# then builds and starts all 9 services + Postgres + MinIO + gateway + frontend.
set -euo pipefail
cd "$(dirname "$0")/.."

ENV_FILE=".env"

if ! command -v docker >/dev/null 2>&1; then
  echo "!! Docker is not installed. Install Docker Engine + the compose plugin first." >&2
  exit 1
fi

rand() { openssl rand -base64 "${1:-36}" | tr -d '\n=+/' | cut -c1-"${2:-32}"; }

if [[ ! -f "$ENV_FILE" ]]; then
  echo "→ Generating $ENV_FILE with fresh strong secrets (gitignored; back it up safely)..."
  cat > "$ENV_FILE" <<EOF
# Generated by launch-prod.sh. KEEP SECRET. This file is gitignored.
DB_NAME=lera
DB_USER=lera
DB_PASSWORD=$(rand 36 32)
# Shared across all services so JWTs validate cross-service. Changing it logs everyone out.
JWT_SECRET=$(rand 64 64)
LERA_STORAGE_BACKEND=minio
MINIO_ROOT_USER=lera
MINIO_ROOT_PASSWORD=$(rand 36 32)
PGADMIN_EMAIL=admin@lera.local
PGADMIN_PASSWORD=$(rand 24 20)
# Optional: set these to enable the respective features
# OPENAI_API_KEY=
# SMTP_HOST=
# SMTP_USER=
# SMTP_PASS=
EOF
  echo "  ✓ secrets written to $ENV_FILE"
else
  echo "→ $ENV_FILE already exists — reusing it."
fi

COMPOSE=(docker compose -f docker-compose.yml)
HTTPS=0
if [[ "${1:-}" == "--https" ]]; then
  : "${DOMAIN:?--https requires DOMAIN=app.your-domain.com (with DNS pointing at this server)}"
  COMPOSE+=(-f docker-compose.https.yml)
  HTTPS=1
  echo "→ HTTPS mode: Caddy will obtain a Let's Encrypt certificate for ${DOMAIN}."
fi

echo "→ Building + starting the stack (first run takes a few minutes)..."
"${COMPOSE[@]}" --env-file "$ENV_FILE" up -d --build

echo
echo "=== Launched ✓ ==="
echo "  health:    ${COMPOSE[*]} ps"
echo "  logs:      ${COMPOSE[*]} logs -f gateway identity_service"
if [[ "$HTTPS" == "1" ]]; then
  echo "  open:      https://${DOMAIN}   (cert provisions within ~30s once DNS points here + :80/:443 are open)"
else
  echo "  open:      http://<this-server-ip>   (front it with Cloudflare for HTTPS, or re-run with --https)"
fi
echo
echo "  IMPORTANT — first-boot admin password is RANDOM. Capture it once:"
echo "    ${COMPOSE[*]} logs identity_service | grep -i 'seed password'"
echo "    (or set lera.seed.* / chairman password via env before first boot)"
echo
echo "  Then verify end-to-end:"
echo "    LERA_BASE_URL=<your-url> LERA_TEST_EMAIL=<admin> LERA_TEST_PASSWORD=<pw> ./scripts/smoke-test-prod.sh"
